// 500 answers for the Book of Answers tool
// Categories: affirmation (20%), denial (15%), suggestion (30%), healing (25%), humor (10%)

export const answers = [
  // === AFFIRMATION (100 answers, ~20%) ===
  "Yes, absolutely.",
  "Without a doubt, go for it.",
  "The answer is clearly yes.",
  "This is your sign to proceed.",
  "Everything aligns in your favor.",
  "You already know the answer — it's yes.",
  "The stars say yes.",
  "Go with full confidence.",
  "This is the right path.",
  "Move forward — the universe supports you.",
  "Yes, and it will be even better than you imagine.",
  "Trust the process — it's going to work out.",
  "The door is open. Walk through it.",
  "Your intuition is right. Say yes.",
  "The answer has been yes all along.",
  "Take the leap. The net will appear.",
  "This is your moment. Embrace it.",
  "The universe is rooting for you.",
  "Yes — and more is coming.",
  "The signs are everywhere. Pay attention.",
  "Your heart already knows. Listen to it.",
  "A resounding yes from the cosmos.",
  "The path is clear. Walk it boldly.",
  "Yes, and the timing is perfect.",
  "Everything is falling into place.",
  "The answer is yes. Now act on it.",
  "Your courage will be rewarded.",
  "This is what you've been waiting for.",
  "The universe whispers: yes.",
  "Say yes to yourself first.",
  "The answer is written in the stars — yes.",
  "Your next chapter starts with yes.",
  "Go boldly where you've never gone before.",
  "Yes — and it's going to be amazing.",
  "The answer was inside you all along: yes.",
  "This is meant to be.",
  "The light is green. Full speed ahead.",
  "Yes, with the full force of the universe behind you.",
  "Your future self will thank you for saying yes.",
  "The answer is a resounding yes.",
  "Take a deep breath and say yes.",
  "The journey of a thousand miles starts with yes.",
  "Yes — the universe has been preparing for this.",
  "Your instincts are sharp. Trust them — it's yes.",
  "The answer is yes. Don't overthink it.",
  "This is your breakthrough moment.",
  "Say yes and watch the magic happen.",
  "The universe conspires to make this happen.",
  "Yes — and you're more ready than you think.",
  "This is the beginning of something great.",
  "The answer is yes. Proceed with joy.",
  "Your wish has been noted and approved.",
  "Yes, with extra sparkle.",
  "The universe nods in agreement.",
  "Your next adventure awaits. Say yes.",
  "Yes — and it will surprise you in the best way.",
  "The answer is yes. Now go make it real.",
  "Your inner compass points to yes.",
  "Yes — the universe loves your ambition.",
  "This is exactly what you need right now.",
  "The answer is yes. Celebrate it.",
  "Yes — and the timing couldn't be better.",
  "Your dream is valid. Go for it.",
  "The universe says yes with a smile.",
  "Yes — and you deserve every bit of it.",
  "Your spirit guides approve.",
  "The answer is yes. Embrace the excitement.",
  "Yes — and it's only the beginning.",
  "Your heart is pointing the right way.",
  "Yes, with the universe as your witness.",
  "This is your sign. Don't ignore it.",
  "The answer is yes. Now go shine.",
  "Yes — and the world needs your light.",
  "Your intuition is your superpower. Trust it.",
  "The answer is yes. Feel the joy.",
  "Yes — and more good things are on the way.",
  "The universe is on your side.",
  "Your next chapter is going to be incredible.",
  "The answer is yes. Own it.",
  "Yes — and you'll be glad you did.",
  "Your soul knows the way. Follow it.",
  "The answer is yes. Start now.",
  "Yes — and everything will align.",
  "Your courage is your compass. Follow it.",
  "The universe delivers: yes.",
  "Yes — with love and confidence.",
  "Your path is illuminated. Walk it.",
  "The answer is yes. Embrace the journey.",
  "Yes — and you're stronger than you know.",
  "The universe applauds your decision.",
  "Yes — and it's going to change everything.",
  "Your inner voice says yes. Listen.",
  "The answer is yes. Take action now.",
  "Yes — and the rewards will surprise you.",
  "Your destiny is calling. Answer yes.",
  "The universe smiles upon your choice.",
  "Yes — and it's your time to shine.",
  "Your spirit soars with this decision.",
  "The answer is yes. Let it be.",

  // === DENIAL (75 answers, ~15%) ===
  "Not now. The timing isn't right.",
  "Pause. Something is missing.",
  "The answer is no — for now.",
  "Wait. There's more to consider.",
  "This isn't the right path.",
  "Hold back. The moment hasn't come.",
  "No — but something better is on the horizon.",
  "The universe says: not yet.",
  "Step back and reassess.",
  "This isn't your season.",
  "Not this one. Keep looking.",
  "The signs point to no.",
  "Hold your ground. The time will come.",
  "No — and that's a blessing in disguise.",
  "The universe has a different plan.",
  "Wait for a clearer sign.",
  "This path leads nowhere new.",
  "No — but don't lose hope.",
  "The timing is wrong. Try again later.",
  "Not this door. Another one will open.",
  "The answer is no. Trust the redirect.",
  "Hold on. There's a better option ahead.",
  "No — and that's okay.",
  "The universe is protecting you from this.",
  "Wait. The puzzle isn't complete yet.",
  "This isn't it. Keep searching.",
  "No — redirect your energy elsewhere.",
  "The answer is no. Breathe and move on.",
  "Not this way. Try a different approach.",
  "The universe says: look elsewhere.",
  "No — but the right answer is closer than you think.",
  "This isn't aligned with your true path.",
  "Wait for the right moment — it's not here yet.",
  "No — and that's the universe being kind.",
  "The signs are clear: this isn't it.",
  "Hold back your energy for something greater.",
  "No — but the universe has something better planned.",
  "Not now. Give it time.",
  "This isn't the mountain you're meant to climb.",
  "The answer is no. Accept it with grace.",
  "Wait. Your intuition is telling you something.",
  "No — and that's the best thing that could happen.",
  "The universe is saying: not this one.",
  "This path is closed for a reason.",
  "No — but don't stop trying.",
  "The timing isn't right. Be patient.",
  "Not this one. The right one is coming.",
  "The answer is no. Look for alternatives.",
  "Wait — there's a lesson here you need to see.",
  "No — and that's your guardian angel protecting you.",
  "This isn't your chapter yet.",
  "The universe says: redirect your focus.",
  "No — but the right path is nearby.",
  "Hold. The answer isn't ready yet.",
  "This isn't the one. Keep your eyes open.",
  "No — and that's the universe making space for better.",
  "Wait for a sign that excites you, not this one.",
  "The answer is no. Move on with confidence.",
  "Not this way. There's a better route.",
  "No — and that's okay. Better is coming.",
  "The universe whispers: try something else.",
  "This isn't your answer. Keep looking.",
  "No — but your patience will be rewarded.",
  "Wait. The right moment is brewing.",
  "This isn't the right fit. Keep searching.",
  "No — and the universe has a backup plan.",
  "Hold your course. This isn't the destination.",
  "The answer is no. Trust that it's for the best.",
  "Not now. The stars aren't aligned.",
  "No — but the right answer is worth waiting for.",
  "This isn't your moment. Yours is coming.",
  "The universe says: look in a different direction.",
  "No — and that's a gift you'll understand later.",
  "Wait. There's more to this story.",
  "This isn't the end. It's a detour.",

  // === SUGGESTION (150 answers, ~30%) ===
  "Look at it from a different angle.",
  "Sleep on it. Clarity comes with rest.",
  "Ask someone you trust for their perspective.",
  "Take a walk. The answer will find you.",
  "Listen more than you speak right now.",
  "Write down your options. Patterns will emerge.",
  "Follow the path of least resistance.",
  "What would your future self advise?",
  "Take a step back and see the bigger picture.",
  "Trust your first instinct — it's usually right.",
  "Talk it out. Sometimes speaking reveals the answer.",
  "Do what makes you feel most alive.",
  "Consider the opposite. What would you do then?",
  "Ask yourself: what am I afraid of?",
  "Let go of perfection. Good enough is good enough.",
  "Follow your curiosity, not your fear.",
  "What does your body tell you? It knows.",
  "Try the thing that scares you a little.",
  "Look for patterns in your past decisions.",
  "Ask: what would I do if I couldn't fail?",
  "Breathe deeply. The answer lives in stillness.",
  "Flip a coin. Your reaction reveals the truth.",
  "What advice would you give a friend in this situation?",
  "Follow the energy. Where does it feel light?",
  "Take one small step and see how it feels.",
  "Journal about it. The pen reveals what the mind hides.",
  "What's the kindest thing you can do for yourself?",
  "Look for signs in the next 24 hours.",
  "Consider the long-term impact, not just the immediate.",
  "What would you regret NOT doing in 10 years?",
  "Follow your joy. It's your compass.",
  "Ask yourself: is this coming from love or fear?",
  "Take a digital detox. Answers come in quiet.",
  "What's the simplest solution? It's usually the right one.",
  "Look at your options without judgment first.",
  "Talk to someone who has walked this path before.",
  "What does your gut say when you stop overthinking?",
  "Try it for one day. See how it feels.",
  "What would you choose if nobody was watching?",
  "Look at what energizes you and what drains you.",
  "Follow the thread that pulls you gently.",
  "Ask: what's the worst that could happen? Can I handle it?",
  "Meditate on it. The answer lives in silence.",
  "What would make your younger self proud?",
  "Look for the option that gives you peace, not anxiety.",
  "Try the unconventional approach. It might be the right one.",
  "What are you avoiding? That's probably the answer.",
  "Ask yourself: what would I do with unlimited time?",
  "Look at your calendar. What do you spend time on? That's your true priority.",
  "Follow the path that feels like home.",
  "What's holding you back? Name it and face it.",
  "Try saying yes to one thing and no to everything else.",
  "Look at your values. Which option aligns with them?",
  "Ask: what would I do if I were braver?",
  "Take a break from deciding. Let your subconscious work.",
  "What feels like play to you and work to others? Do that.",
  "Look at the evidence, not just the emotion.",
  "Ask someone who knows you well what they think.",
  "What's the option that scares you but also excites you?",
  "Follow the data. What do the facts say?",
  "Look at your priorities. What comes first?",
  "What would you do if you knew you'd succeed?",
  "Try the opposite of what you'd normally do.",
  "Ask: what am I not seeing right now?",
  "Look for the option that brings you peace of mind.",
  "What's the most loving choice you can make?",
  "Follow your creative impulse. It's guiding you.",
  "Ask yourself: what story do I want to tell about this?",
  "Look at what you're drawn to. That's your answer.",
  "Try setting a deadline. Decisions love deadlines.",
  "What's the option that aligns with your values?",
  "Ask: what would I do if I had nothing to lose?",
  "Look at the situation from a bird's-eye view.",
  "Follow the option that makes you feel expansive, not contracted.",
  "What's the simplest next step? Take it.",
  "Ask yourself: what would I regret more — doing it or not doing it?",
  "Look at what brings you alive. Follow that thread.",
  "Try writing a letter to yourself about this decision.",
  "What's the option that feels most authentic to you?",
  "Ask: what would I do if I trusted myself completely?",
  "Look at your patterns. What keeps repeating?",
  "Follow the path that makes you feel most like yourself.",
  "What's the option that aligns with your long-term vision?",
  "Ask yourself: what's the story I'm telling myself about this?",
  "Look at what you're resisting. That's often where growth is.",
  "Try the option that feels both scary and right.",
  "What's the choice that honors both your head and your heart?",
  "Ask: what would I do if I were my own best friend?",
  "Look at what feels inevitable. That's probably your answer.",
  "Follow the path that feels like coming home.",
  "What's the option that you keep coming back to?",
  "Ask yourself: what would I do if I let go of all expectations?",
  "Look at the situation with fresh eyes tomorrow.",
  "Try the approach that feels most natural to you.",
  "What's the choice that you'll be proud of later?",
  "Ask: what's the smallest step I can take right now?",
  "Look at what you're most curious about. Follow it.",
  "Follow the option that feels like an expansion of who you are.",
  "What's the decision that aligns with your deepest values?",
  "Ask yourself: what would I do if I believed in myself?",
  "Look at the path that calls to your soul.",
  "Try the option that feels most alive to you.",
  "What's the choice that brings you closer to your true self?",
  "Ask: what would I do if I stopped worrying about what others think?",
  "Look at what you're avoiding. The answer is often there.",
  "Follow the path that feels like destiny.",
  "What's the option that makes you feel most whole?",
  "Ask yourself: what would I do if I knew I was loved unconditionally?",
  "Look at the choice that feels most courageous.",
  "Try the path that feels like an adventure.",
  "What's the decision that honors your inner wisdom?",
  "Ask: what would I do if I trusted the process?",
  "Look at the option that feels like truth.",
  "Follow the path that resonates with your deepest self.",
  "What's the choice that makes you feel most free?",
  "Ask yourself: what would I do if I embraced uncertainty?",
  "Look at what you're drawn to in your dreams. That's a clue.",
  "Try the option that feels like home in your heart.",
  "What's the decision that aligns with your soul's purpose?",
  "Ask: what would I do if I let love be my guide?",
  "Look at the path that makes you feel most authentic.",
  "Follow the option that feels like the next chapter.",
  "What's the choice that brings you closer to who you want to be?",
  "Ask yourself: what would I do if I chose joy over fear?",
  "Look at the option that feels like a gentle nudge from the universe.",
  "Try the path that feels like a deep breath of fresh air.",
  "What's the decision that feels most aligned with your truth?",
  "Ask: what would I do if I believed anything was possible?",
  "Look at what you're passionate about. That's your compass.",
  "Follow the path that feels like a conversation with your soul.",
  "What's the choice that makes you feel most at peace?",
  "Ask yourself: what would I do if I listened to my heart?",
  "Look at the option that feels like the missing piece.",
  "Try the decision that feels like a yes from your entire being.",
  "What's the path that feels like it was meant for you?",
  "Ask: what would I do if I chose courage over comfort?",
  "Look at what makes you feel most alive. That's your answer.",
  "Follow the option that feels like a whisper from the universe.",
  "What's the decision that brings you closer to your dreams?",
  "Ask yourself: what would I do if I trusted my intuition completely?",
  "Look at the path that feels like a gift waiting to be unwrapped.",
  "Try the choice that feels like the right next step.",
  "What's the option that makes you feel most connected?",
  "Ask: what would I do if I chose faith over fear?",
  "Look at what you're called to do. That's your answer.",
  "Follow the path that feels like coming home to yourself.",

  // === HEALING (125 answers, ~25%) ===
  "Let it go. It was never yours to carry.",
  "Everything happens for a reason. Trust the process.",
  "You are exactly where you need to be.",
  "This too shall pass.",
  "Breathe. You've survived 100% of your bad days so far.",
  "Be gentle with yourself. You're doing your best.",
  "The universe is working on it behind the scenes.",
  "You are loved more than you know.",
  "What's meant for you will never miss you.",
  "Release what no longer serves you.",
  "Your struggle is shaping you into who you need to be.",
  "The best is yet to come.",
  "You don't have to have it all figured out.",
  "Trust the timing of your life.",
  "What you seek is seeking you.",
  "Let the river carry you for a while.",
  "You are stronger than you think.",
  "The universe has a plan bigger than you can see.",
  "Be patient. Good things take time.",
  "You are worthy of good things.",
  "Let go and let the universe handle it.",
  "Your worth is not measured by your productivity.",
  "The storm will pass. You will too.",
  "You are enough, just as you are.",
  "What's coming is better than what's gone.",
  "Rest. You've earned it.",
  "The answer will come when you're ready to receive it.",
  "You are not alone. You never were.",
  "The universe is holding you, even when you can't feel it.",
  "Give yourself permission to heal.",
  "Everything is working out, even when it doesn't look like it.",
  "You are growing through what you're going through.",
  "Let the old version of you go. A new one is rising.",
  "You are doing better than you think you are.",
  "The universe is rearranging things in your favor.",
  "Take it one day at a time. That's enough.",
  "You are allowed to change your mind.",
  "The hardest chapters lead to the best endings.",
  "You are worthy of love and happiness.",
  "Let yourself be a work in progress.",
  "The universe sees your effort. Keep going.",
  "You don't need to earn rest. Take it.",
  "What feels like an ending is a beginning in disguise.",
  "You are surrounded by blessings you haven't noticed yet.",
  "Be kind to yourself. You're human.",
  "The universe is teaching you something through this.",
  "You will get through this. You always do.",
  "Let go of what you can't control.",
  "You are becoming who you were always meant to be.",
  "The light is always there, even in the darkness.",
  "You deserve peace. Claim it.",
  "The universe is preparing you for something beautiful.",
  "Give yourself grace. You're learning.",
  "You are more resilient than you know.",
  "The answer is peace. Choose it.",
  "Let the universe surprise you.",
  "You are held in love, always.",
  "What's meant to be will be. Relax.",
  "You are exactly on time. Not early, not late.",
  "The universe is writing your story. Trust the author.",
  "Be still. The answer will find you in the quiet.",
  "You are worthy of the life you dream of.",
  "Let go of the need to know everything.",
  "The universe is on your side, always.",
  "You are becoming. And that's enough.",
  "What you're going through is preparing you for what you're going to.",
  "Rest your mind. The answers will come.",
  "You are loved. That will never change.",
  "The universe is guiding you, even when the path is unclear.",
  "You are allowed to take up space.",
  "Let the healing begin. You're ready.",
  "You are a miracle. Never forget that.",
  "The universe is working miracles you can't see yet.",
  "You are safe. You are loved. You are enough.",
  "Let go of the weight. It was never yours.",
  "You are exactly where the universe needs you to be.",
  "The darkness is just a canvas for the light to shine.",
  "You are worthy of every good thing coming your way.",
  "Breathe. The universe has your back.",
  "You are growing. Give yourself credit.",
  "The universe is aligning everything for your highest good.",
  "Let yourself be guided. You don't have to drive.",
  "You are a masterpiece in progress.",
  "The answer is love. Always love.",
  "You are exactly who you need to be right now.",
  "The universe sees your pain. It won't last forever.",
  "Let go of perfection. Embrace progress.",
  "You are worthy of the love you give to others.",
  "The universe is your ally. Trust it.",
  "You are healing, even when you don't feel it.",
  "Let the universe take the wheel for a moment.",
  "You are a light in this world. Don't dim yourself.",
  "The universe is whispering: you're going to be okay.",
  "You are allowed to take things slow.",
  "Let yourself be soft. Strength isn't always hard.",
  "You are worthy of rest, play, and joy.",
  "The universe is holding space for your healing.",
  "You are becoming your best self, one day at a time.",
  "Let go of the outcome. Focus on the journey.",
  "You are a gift to this world. Remember that.",
  "The universe is weaving your story with care.",
  "You are exactly where you're supposed to be.",
  "Let the answers come to you in their own time.",
  "You are worthy of the peace you seek.",
  "The universe is turning your pain into power.",
  "You are loved beyond measure.",
  "Let yourself be guided by what feels right.",
  "You are a beautiful work of art in progress.",
  "The universe is your biggest fan.",
  "You are allowed to bloom at your own pace.",
  "Let the universe surprise you with its goodness.",
  "You are exactly the person the world needs.",
  "The universe is preparing a miracle for you.",
  "You are worthy of every opportunity that comes your way.",
  "Let go of worry. The universe is handling it.",
  "You are growing into the person you were meant to be.",
  "The universe is writing the most beautiful chapter for you.",
  "You are enough. You always have been.",
  "Let yourself be happy. It's your birthright.",
  "You are a force of nature. Never forget that.",
  "The universe is aligning the stars in your favor.",
  "You are worthy of the life you're building.",
  "Let the universe do its work. You've done yours.",
  "You are a miracle walking. Remember that daily.",
  "The universe is guiding you home, one step at a time.",
  "You are allowed to take up all the space you need.",
  "Let yourself be guided by love, not fear.",
  "You are exactly the right person for this moment.",
  "The universe is conspiring in your favor.",
  "You are worthy of the happiness that's coming.",
  "Let go. Trust. Receive. That's all you need to do.",
  "You are a beacon of light in this world.",
  "The universe is holding you through every storm.",
  "You are becoming. Trust the transformation.",
  "Let yourself be carried by the current of life.",
  "You are worthy of love, joy, and everything beautiful.",
  "The universe is your guardian. Rest in that knowledge.",
  "You are exactly where you need to be. Right now. This moment.",
  "Let the universe remind you how far you've come.",
  "You are a miracle. Act like one.",
  "The universe is preparing you for your greatest chapter.",
  "You are worthy of the dreams you carry.",
  "Let yourself be guided by your highest self.",

  // === HUMOR (50 answers, ~10%) ===
  "Sleep on it. Tomorrow you'll have a better answer.",
  "Ask again after coffee.",
  "The answer is 42. Now go figure out the question.",
  "Have you tried turning it off and on again?",
  "Ask your cat. They always know.",
  "The answer is in the last place you look. So look there first.",
  "Flip a coin. If you're disappointed with the result, you already know.",
  "Consult the ancient wisdom of your refrigerator.",
  "The answer is: order pizza and think about it.",
  "Google it. Then ask your mom. Then decide.",
  "The answer will come to you in the shower. It always does.",
  "Ask your plants. They're great listeners.",
  "The universe says: lol good luck with that.",
  "Check your horoscope. Then ignore it and do what you want.",
  "The answer is: dance it out. Then decide.",
  "Ask the nearest dog. They live their best life.",
  "The answer is hiding in your browser history.",
  "Consult your inner child. They have surprisingly good advice.",
  "The answer is: take a nap. The answer will be clearer after.",
  "Ask the moon. It's been watching over you.",
  "The answer is: eat something delicious first. Then decide.",
  "Flip a coin and see if you catch it. That's your answer.",
  "Ask your best friend. Then do the opposite. Just kidding. Maybe.",
  "The answer is: procrastinate until the deadline forces a decision.",
  "Ask a 5-year-old. They haven't learned to overthink yet.",
  "The answer is: go for a walk and let the universe text you.",
  "Consult your playlist. Whatever song is playing is your sign.",
  "The answer is: make a pros and cons list, then burn it and decide with your heart.",
  "Ask your grandmother. She's seen it all.",
  "The answer is: laugh about it. Then decide. Then laugh again.",
  "Flip a coin. While it's in the air, you'll know what you hope it lands on.",
  "Ask the nearest stranger for advice. They have nothing to lose.",
  "The answer is: do what you'd do in a movie. That's always the right answer.",
  "Consult a magic 8-ball. Then do the opposite. Or follow it. Who knows?",
  "The answer is: sing your question to the tune of your favorite song.",
  "Ask your future self via journaling. They're wiser than you think.",
  "The answer is: make a decision and pretend it's a game.",
  "Ask the universe for a sign. Then watch for it like a hawk.",
  "The answer is: do the thing that makes you feel like a kid again.",
  "Flip three coins. Majority wins. Best two out of three.",
  "Ask your mirror. But only if you're ready for brutal honesty.",
  "The answer is: do nothing and see what happens. Sometimes that's the best strategy.",
  "Ask the WiFi router. It connects everything, maybe it can connect you to an answer.",
  "The answer is: make a decision based on what would make a good story.",
  "Ask the nearest tree. Trees have been making decisions for centuries.",
  "The answer is: do the thing that would make your 80-year-old self proud.",
  "Flip a coin. But if it lands on the edge, that means maybe.",
  "Ask your inner comedian. What's the funniest option? Do that.",
  "The answer is: whatever you choose, make sure there's dessert involved.",
  "Ask the universe for a sign, and if you see a rainbow, that's definitely it.",
  "The answer is: do what you'd recommend to your best friend, then add extra courage.",
];
