export interface FoodItem {
  id: string;
  name: string;
  nameEs: string;
  nameAr: string;
  category: "quick-lunch" | "budget-meals" | "fitness-diet" | "comfort-food";
  emoji: string;
  calories: string; // e.g. "450-550 kcal"
  desc: string;
  descEs: string;
  descAr: string;
}

export interface FoodCategory {
  id: FoodItem["category"];
  name: string;
  nameEs: string;
  nameAr: string;
  icon: string;
  color: string; // tailwind classes
}

export const foodCategories: FoodCategory[] = [
  {
    id: "quick-lunch",
    name: "Quick & Easy Lunch",
    nameEs: "Almuerzo Rápido",
    nameAr: "غداء سريع وسهل",
    icon: "🥪",
    color: "bg-amber-50 border-amber-200 text-amber-800 dark:bg-amber-950/30 dark:border-amber-700 dark:text-amber-300",
  },
  {
    id: "budget-meals",
    name: "Budget-Friendly Meals",
    nameEs: "Comidas Económicas",
    nameAr: "وجبات اقتصادية",
    icon: "🍝",
    color: "bg-green-50 border-green-200 text-green-800 dark:bg-green-950/30 dark:border-green-700 dark:text-green-300",
  },
  {
    id: "fitness-diet",
    name: "Fitness & Healthy",
    nameEs: "Saludable & Fitness",
    nameAr: "صحي ولياقة",
    icon: "🥗",
    color: "bg-emerald-50 border-emerald-200 text-emerald-800 dark:bg-emerald-950/30 dark:border-emerald-700 dark:text-emerald-300",
  },
  {
    id: "comfort-food",
    name: "Comfort Food",
    nameEs: "Comida Reconfortante",
    nameAr: "طعام مريح",
    icon: "🍕",
    color: "bg-rose-50 border-rose-200 text-rose-800 dark:bg-rose-950/30 dark:border-rose-700 dark:text-rose-300",
  },
];

export const foodItems: FoodItem[] = [
  // ===== QUICK & EASY LUNCH (上班族简餐) =====
  {
    id: "turkey-club-sandwich",
    name: "Turkey Club Sandwich",
    nameEs: "Sándwich Club de Pavo",
    nameAr: "ساندويتش الديك الرومي",
    category: "quick-lunch",
    emoji: "🥪",
    calories: "450-550 kcal",
    desc: "Triple-decker with roasted turkey, crispy bacon, lettuce, tomato, and mayo on toasted bread.",
    descEs: "Sándwich triple con pavo asado, tocino crujiente, lechuga, tomate y mayonesa en pan tostado.",
    descAr: "ساندويتش ثلاثي الطبقات مع ديك رومي مشوي ولحم مقدد مقرمش وخس وطماطم ومايونيز على خبز محمص.",
  },
  {
    id: "caesar-salad-wrap",
    name: "Caesar Salad Wrap",
    nameEs: "Wrap de Ensalada César",
    nameAr: "لفافة سلطة سيزر",
    category: "quick-lunch",
    emoji: "🌯",
    calories: "380-450 kcal",
    desc: "Grilled chicken, romaine lettuce, parmesan, croutons, and Caesar dressing in a flour tortilla.",
    descEs: "Pollo a la parrilla, lechuga romana, parmesano, crutones y aderezo César en tortilla de harina.",
    descAr: "دجاج مشوي وخس روماني وبارميزان وخبز محمص وصلصة سيزر في خبز تورتيا.",
  },
  {
    id: "grilled-chicken-panini",
    name: "Grilled Chicken Panini",
    nameEs: "Panini de Pollo a la Parrilla",
    nameAr: "بانيني الدجاج المشوي",
    category: "quick-lunch",
    emoji: "🥖",
    calories: "480-550 kcal",
    desc: "Pressed Italian sandwich with grilled chicken, mozzarella, sun-dried tomatoes, and pesto aioli.",
    descEs: "Sándwich italiano prensado con pollo a la parrilla, mozzarella, tomates secos y alioli de pesto.",
    descAr: "ساندويتش إيطالي مضغوط مع دجاج مشوي وجبن موزاريلا وطماطم مجففة وأيولي البيستو.",
  },
  {
    id: "quiche-lorraine",
    name: "Quiche Lorraine",
    nameEs: "Quiche Lorraine",
    nameAr: "كيش لورين",
    category: "quick-lunch",
    emoji: "🥧",
    calories: "420-500 kcal",
    desc: "Classic French savory tart with bacon, Gruyère cheese, and egg custard in a buttery crust.",
    descEs: "Clásica tarta salada francesa con tocino, queso Gruyère y crema de huevo en corteza de mantequilla.",
    descAr: "تارت فرنسي كلاسيكي بالبيكون وجبن غرويير وكاسترد البيض في قشرة زبدية.",
  },
  {
    id: "caprese-panini",
    name: "Caprese Panini",
    nameEs: "Panini Caprese",
    nameAr: "بانيني كابريزي",
    category: "quick-lunch",
    emoji: "🥖",
    calories: "380-430 kcal",
    desc: "Fresh mozzarella, sliced tomatoes, basil leaves, and balsamic glaze pressed between ciabatta.",
    descEs: "Mozzarella fresca, tomates en rodajas, hojas de albahaca y glaseado balsámico prensado en ciabatta.",
    descAr: "جبن موزاريلا طازج وشرائح طماطم وأوراق ريحان وصوص بلسمي مضغوط بين خبز سياباتا.",
  },
  {
    id: "chicken-avocado-toast",
    name: "Chicken Avocado Toast",
    nameEs: "Tostada de Pollo y Aguacate",
    nameAr: "توست الدجاج والأفوكادو",
    category: "quick-lunch",
    emoji: "🥑",
    calories: "350-420 kcal",
    desc: "Sourdough toast topped with smashed avocado, sliced grilled chicken, cherry tomatoes, and everything bagel seasoning.",
    descEs: "Tostada de masa madre con puré de aguacate, pollo a la parrilla en rodajas, tomates cherry y condimento everything bagel.",
    descAr: "توست العجين المخمر مع أفوكادو مهروس وشرائح دجاج مشوي وطماطم كرزية وبهارات الخبز.",
  },
  {
    id: "tuna-nicoise-bowl",
    name: "Tuna Niçoise Bowl",
    nameEs: "Bol de Atún Niçoise",
    nameAr: "طبق التونة نيسواز",
    category: "quick-lunch",
    emoji: "🥗",
    calories: "400-480 kcal",
    desc: "Seared tuna, boiled eggs, green beans, olives, potatoes, and mixed greens with Dijon vinaigrette.",
    descEs: "Atún sellado, huevos duros, judías verdes, aceitunas, papas y verduras mixtas con vinagreta de Dijon.",
    descAr: "تونة مشوية وبيض مسلوق وفاصوليا خضراء وزيتون وبطاطس وخضروات مشكلة مع صلصة ديجون.",
  },
  {
    id: "italian-sub",
    name: "Italian Sub",
    nameEs: "Sándwich Italiano",
    nameAr: "ساندويتش إيطالي",
    category: "quick-lunch",
    emoji: "🥖",
    calories: "520-620 kcal",
    desc: "Loaded sub roll with salami, ham, provolone, lettuce, tomato, onion, pepperoncini, and Italian dressing.",
    descEs: "Panecillo relleno con salami, jamón, provolone, lechuga, tomate, cebolla, pepperoncini y aderezo italiano.",
    descAr: "خبز محشو بالسجق المجفف ولحم الخنزير وجبن بروفولون وخس وطماطم وبصل وفلفل مخلل وصوص إيطالي.",
  },
  {
    id: "thai-chicken-wrap",
    name: "Thai Chicken Wrap",
    nameEs: "Wrap de Pollo Tailandés",
    nameAr: "لفافة الدجاج التايلاندية",
    category: "quick-lunch",
    emoji: "🌯",
    calories: "400-470 kcal",
    desc: "Grilled chicken, shredded carrots, red cabbage, cilantro, crushed peanuts, and spicy peanut sauce in a wrap.",
    descEs: "Pollo a la parrilla, zanahoria rallada, col roja, cilantro, maní triturado y salsa picante de maní en un wrap.",
    descAr: "دجاج مشوي وجزر مبشور وملفوف أحمر وكزبرة وفول سوداني مطحون وصلصة فول سوداني حارة في لفافة.",
  },
  {
    id: "soup-and-salad-combo",
    name: "Soup & Salad Combo",
    nameEs: "Combo de Sopa y Ensalada",
    nameAr: "طبق حساء وسلطة",
    category: "quick-lunch",
    emoji: "🍜",
    calories: "300-450 kcal",
    desc: "Half sandwich or soup of the day paired with a fresh garden salad. Light yet satisfying lunch classic.",
    descEs: "Medio sándwich o sopa del día acompañado de ensalada fresca. Clásico ligero pero satisfactorio.",
    descAr: "نصف ساندويتش أو حساء اليوم مع سلطة طازجة. غداء كلاسيكي خفيف ومشبع.",
  },
  {
    id: "mediterranean-flatbread",
    name: "Mediterranean Flatbread",
    nameEs: "Pan Plano Mediterráneo",
    nameAr: "خبز مسطح متوسطي",
    category: "quick-lunch",
    emoji: "🫓",
    calories: "420-500 kcal",
    desc: "Warm flatbread topped with hummus, roasted red peppers, feta, olives, arugula, and lemon-herb drizzle.",
    descEs: "Pan plano caliente con hummus, pimientos rojos asados, feta, aceitunas, rúcula y aderezo de limón y hierbas.",
    descAr: "خبز مسطح دافئ مع حمص وفلفل أحمر محمص وجبن فيتا وزيتون وجرجير وصوص ليمون بالأعشاب.",
  },
  {
    id: "asian-chicken-salad",
    name: "Asian Chicken Salad",
    nameEs: "Ensalada de Pollo Asiática",
    nameAr: "سلطة الدجاج الآسيوية",
    category: "quick-lunch",
    emoji: "🥗",
    calories: "350-430 kcal",
    desc: "Grilled teriyaki chicken, mixed greens, mandarin oranges, crispy wontons, almonds, and sesame ginger dressing.",
    descEs: "Pollo teriyaki a la parrilla, verduras mixtas, mandarinas, wonton crujiente, almendras y aderezo de sésamo y jengibre.",
    descAr: "دجاج ترياكي مشوي وخضروات مشكلة وبرتقال ماندرين ووانتون مقرمش ولوز وصلصة زنجبيل بالسمسم.",
  },
  {
    id: "bagel-with-lox",
    name: "Bagel with Lox",
    nameEs: "Bagel con Salmón",
    nameAr: "خبز بيغل مع السلمون",
    category: "quick-lunch",
    emoji: "🥯",
    calories: "380-480 kcal",
    desc: "Toasted bagel with cream cheese, smoked salmon, capers, red onion, and fresh dill. NYC deli classic.",
    descEs: "Bagel tostado con queso crema, salmón ahumado, alcaparras, cebolla roja y eneldo fresco. Clásico de Nueva York.",
    descAr: "خبز بيغل محمص مع جبن كريمي وسلمون مدخن وكبر وبصل أحمر وشبت طازج. طبق نيويوركي كلاسيكي.",
  },
  {
    id: "greek-salad-pita",
    name: "Greek Salad Pita",
    nameEs: "Pita de Ensalada Griega",
    nameAr: "بيتا سلطة يونانية",
    category: "quick-lunch",
    emoji: "🫓",
    calories: "340-420 kcal",
    desc: "Warm pita stuffed with cucumber, tomato, red onion, kalamata olives, feta, and Greek yogurt dressing.",
    descEs: "Pita caliente rellena de pepino, tomate, cebolla roja, aceitunas kalamata, feta y aderezo de yogur griego.",
    descAr: "خبز بيتا دافئ محشو بالخيار والطماطم والبصل الأحمر وزيتون كالاماتا وجبن فيتا وصلصة زبادي يونانية.",
  },
  {
    id: "bbq-chicken-quesadilla",
    name: "BBQ Chicken Quesadilla",
    nameEs: "Quesadilla de Pollo BBQ",
    nameAr: "كويساديا الدجاج بالباربيكيو",
    category: "quick-lunch",
    emoji: "🫔",
    calories: "480-580 kcal",
    desc: "Crispy flour tortilla filled with BBQ shredded chicken, cheddar-jack cheese, red onion, and cilantro.",
    descEs: "Tortilla de harina crujiente rellena de pollo desmenuzado BBQ, queso cheddar-jack, cebolla roja y cilantro.",
    descAr: "تورتيا طحين مقرمشة محشوة بالدجاج المبهر بصلصة الباربيكيو وجبن شيدر وبصل أحمر وكزبرة.",
  },

  // ===== BUDGET-FRIENDLY MEALS (学生平价餐) =====
  {
    id: "classic-spaghetti",
    name: "Classic Spaghetti Bolognese",
    nameEs: "Espaguetis a la Boloñesa",
    nameAr: "سباغيتي بولونيز",
    category: "budget-meals",
    emoji: "🍝",
    calories: "550-650 kcal",
    desc: "Hearty pasta with rich beef-tomato sauce, garlic, onions, and herbs. The ultimate budget comfort staple.",
    descEs: "Pasta abundante con rica salsa de carne de res y tomate, ajo, cebolla y hierbas. El básico económico definitivo.",
    descAr: "معكرونة شهية مع صلصة لحم البقر والطماطم الغنية والثوم والبصل والأعشاب. الطبق الاقتصادي المثالي.",
  },
  {
    id: "mac-and-cheese",
    name: "Mac & Cheese",
    nameEs: "Macarrones con Queso",
    nameAr: "معكرونة بالجبن",
    category: "budget-meals",
    emoji: "🧀",
    calories: "450-550 kcal",
    desc: "Creamy, cheesy elbow macaroni with a crispy breadcrumb topping. Baked golden and bubbly.",
    descEs: "Macarrones cremosos con queso y cobertura crujiente de pan rallado. Horneados dorados y burbujeantes.",
    descAr: "معكرونة كريمية بالجبن مع طبقة مقرمشة من فتات الخبز. مخبوزة حتى تصبح ذهبية وفقاعية.",
  },
  {
    id: "ramen-upgrade",
    name: "Upgraded Instant Ramen",
    nameEs: "Ramen Instantáneo Mejorado",
    nameAr: "رامين سريع التحضير مطور",
    category: "budget-meals",
    emoji: "🍜",
    calories: "400-500 kcal",
    desc: "Instant ramen elevated with soft-boiled egg, green onions, corn, nori, and a drizzle of sesame oil.",
    descEs: "Ramen instantáneo mejorado con huevo tibio, cebollines, elote, nori y un chorrito de aceite de sésamo.",
    descAr: "رامين سريع التحضير مطور مع بيض نصف مسلوق وبصل أخضر وذرة ونوري وقليل من زيت السمسم.",
  },
  {
    id: "bean-cheese-burrito",
    name: "Bean & Cheese Burrito",
    nameEs: "Burrito de Frijoles y Queso",
    nameAr: "بوريتو الفاصوليا والجبن",
    category: "budget-meals",
    emoji: "🌯",
    calories: "480-580 kcal",
    desc: "Large flour tortilla stuffed with refried beans, melted cheddar, rice, and salsa. Filling and cheap.",
    descEs: "Tortilla de harina grande rellena de frijoles refritos, queso cheddar derretido, arroz y salsa. Sacia y es barato.",
    descAr: "تورتيا طحين كبيرة محشوة بالفاصوليا المقلية وجبن شيدر مذاب وأرز وصلصة. مشبعة ورخيصة.",
  },
  {
    id: "tuna-melt-sandwich",
    name: "Tuna Melt Sandwich",
    nameEs: "Sándwich de Atún Fundido",
    nameAr: "ساندويتش التونة المذابة",
    category: "budget-meals",
    emoji: "🥪",
    calories: "400-500 kcal",
    desc: "Classic diner-style open-faced tuna salad with melted cheddar on toasted bread. Made with canned tuna.",
    descEs: "Clásico sándwich abierto de ensalada de atún estilo diner con queso cheddar derretido en pan tostado.",
    descAr: "ساندويتش تونة كلاسيكي مفتوح على طراز المطاعم مع جبن شيدر مذاب على خبز محمص. مصنوع من التونة المعلبة.",
  },
  {
    id: "egg-fried-rice",
    name: "Egg Fried Rice",
    nameEs: "Arroz Frito con Huevo",
    nameAr: "أرز مقلي بالبيض",
    category: "budget-meals",
    emoji: "🍚",
    calories: "380-480 kcal",
    desc: "Quick stir-fried rice with scrambled egg, peas, carrots, and soy sauce. Better than takeout, pennies per serving.",
    descEs: "Arroz salteado rápido con huevo revuelto, guisantes, zanahorias y salsa de soja. Mejor que el delivery.",
    descAr: "أرز مقلي سريع مع بيض مخفوق وبازلاء وجزر وصلصة صويا. أفضل من الطلبات الخارجية.",
  },
  {
    id: "grilled-cheese-soup",
    name: "Grilled Cheese + Tomato Soup",
    nameEs: "Sándwich de Queso Fundido + Sopa de Tomate",
    nameAr: "ساندويتش جبن مشوي + حساء طماطم",
    category: "budget-meals",
    emoji: "🥫",
    calories: "420-520 kcal",
    desc: "Golden buttery grilled cheese paired with warm tomato soup for dipping. The ultimate budget comfort duo.",
    descEs: "Sándwich de queso dorado y mantecoso combinado con sopa de tomate caliente para mojar.",
    descAr: "ساندويتش جبن ذهبي بالزبدة مع حساء طماطم دافئ للتغميس. الثنائي المريح الاقتصادي المثالي.",
  },
  {
    id: "chicken-rice-bowl",
    name: "Chicken Rice Bowl",
    nameEs: "Bol de Arroz con Pollo",
    nameAr: "طبق أرز بالدجاج",
    category: "budget-meals",
    emoji: "🍚",
    calories: "450-550 kcal",
    desc: "Simple seasoned chicken thighs over steamed rice with steamed broccoli and teriyaki drizzle.",
    descEs: "Muslos de pollo sazonados sobre arroz al vapor con brócoli y salsa teriyaki.",
    descAr: "أفخاذ دجاج متبلة على أرز مطهو بالبخار مع بروكلي وصلصة ترياكي.",
  },
  {
    id: "loaded-baked-potato",
    name: "Loaded Baked Potato",
    nameEs: "Papa al Horno Cargada",
    nameAr: "بطاطس مخبوزة محملة",
    category: "budget-meals",
    emoji: "🥔",
    calories: "400-500 kcal",
    desc: "Fluffy baked potato fully loaded with sour cream, cheddar, bacon bits, and chives. Hearty and under $3.",
    descEs: "Papa al horno esponjosa completamente cargada con crema agria, queso cheddar, trocitos de tocino y cebollino.",
    descAr: "بطاطس مخبوزة هشة محملة بالكريمة الحامضة وجبن شيدر وقطع لحم مقدد وثوم معمر. مشبعة وأقل من 3 دولارات.",
  },

  {
    id: "sloppy-joes",
    name: "Sloppy Joes",
    nameEs: "Sloppy Joes",
    nameAr: "سلوبي جو",
    category: "budget-meals",
    emoji: "🍔",
    calories: "400-520 kcal",
    desc: "Seasoned ground beef in tangy tomato sauce piled on a soft hamburger bun. Messy, sweet, and totally satisfying.",
    descEs: "Carne molida sazonada en salsa de tomate sobre pan de hamburguesa suave. Desordenado, dulce y muy satisfactorio.",
    descAr: "لحم بقري مفروم متبل في صلصة طماطم منعشة على خبز همبرغر طري. فوضوي وحلو ومرضٍ تماماً.",
  },
  {
    id: "pasta-aglio-olio",
    name: "Spaghetti Aglio e Olio",
    nameEs: "Espaguetis Aglio e Olio",
    nameAr: "سباغيتي أغليو إي أوليو",
    category: "budget-meals",
    emoji: "🍝",
    calories: "350-450 kcal",
    desc: "Simple Italian classic — spaghetti tossed with garlic sautéed in olive oil, red pepper flakes, and parsley. 5 ingredients max.",
    descEs: "Clásico italiano simple: espaguetis mezclados con ajo salteado en aceite de oliva, hojuelas de chile rojo y perejil. Máximo 5 ingredientes.",
    descAr: "طبق إيطالي بسيط كلاسيكي - سباغيتي مقلية بالثوم في زيت الزيتون ورقائق الفلفل الأحمر والبقدونس. 5 مكونات كحد أقصى.",
  },
  {
    id: "chickpea-curry",
    name: "Quick Chickpea Curry",
    nameEs: "Curry Rápido de Garbanzos",
    nameAr: "كاري الحمص السريع",
    category: "budget-meals",
    emoji: "🍛",
    calories: "380-480 kcal",
    desc: "Canned chickpeas simmered in spiced coconut-tomato sauce, served over rice. Pantry-friendly, ready in 20 minutes.",
    descEs: "Garbanzos enlatados cocidos a fuego lento en salsa de coco y tomate especiada, servidos sobre arroz. Listo en 20 minutos.",
    descAr: "حمص معلب مطهو ببطء في صلصة جوز الهند والطماطم المتبلة، يقدم فوق الأرز. جاهز في 20 دقيقة.",
  },
  {
    id: "tuna-pasta-salad",
    name: "Tuna Pasta Salad",
    nameEs: "Ensalada de Pasta con Atún",
    nameAr: "سلطة المعكرونة بالتونة",
    category: "budget-meals",
    emoji: "🥗",
    calories: "380-480 kcal",
    desc: "Cold rotini pasta with canned tuna, sweet corn, peas, and light mayo. Great for meal-prep, stays fresh for days.",
    descEs: "Pasta rotini fría con atún enlatado, elote dulce, guisantes y mayonesa ligera. Ideal para preparar con anticipación.",
    descAr: "معكرونة روتيني باردة مع تونة معلبة وذرة حلوة وبازلاء ومايونيز خفيف. رائع للتحضير المسبق.",
  },
  {
    id: "cheese-quesadilla",
    name: "Cheese Quesadilla with Salsa",
    nameEs: "Quesadilla de Queso con Salsa",
    nameAr: "كويساديا الجبن مع الصلصة",
    category: "budget-meals",
    emoji: "🫔",
    calories: "350-450 kcal",
    desc: "Crispy golden tortilla filled with melted cheese blend, served with sour cream and fresh salsa. Ready in 5 minutes.",
    descEs: "Tortilla dorada y crujiente rellena de mezcla de quesos derretidos, con crema agria y salsa fresca. Lista en 5 minutos.",
    descAr: "تورتيا ذهبية مقرمشة محشوة بخليط جبن مذاب، تقدم مع كريمة حامضة وصلصة طازجة. جاهزة في 5 دقائق.",
  },
  {
    id: "pita-pizza",
    name: "Pita Bread Pizza",
    nameEs: "Pizza de Pan Pita",
    nameAr: "بيتزا خبز البيتا",
    category: "budget-meals",
    emoji: "🍕",
    calories: "300-400 kcal",
    desc: "Store-bought pita topped with tomato sauce, shredded mozzarella, and your favorite toppings. Baked in 8 minutes.",
    descEs: "Pan pita comprado cubierto con salsa de tomate, mozzarella rallada y tus ingredientes favoritos. Horneado en 8 minutos.",
    descAr: "خبز بيتا جاهز مغطى بصلصة طماطم وجبن موزاريلا مبشور وإضافاتك المفضلة. يخبز في 8 دقائق.",
  },
  {
    id: "black-bean-soup",
    name: "Hearty Black Bean Soup",
    nameEs: "Sopa de Frijoles Negros",
    nameAr: "حساء الفاصوليا السوداء",
    category: "budget-meals",
    emoji: "🍲",
    calories: "280-380 kcal",
    desc: "Canned black beans transformed into a rich, smoky soup with cumin, garlic, and lime. Top with sour cream and tortilla strips.",
    descEs: "Frijoles negros enlatados transformados en una sopa rica y ahumada con comino, ajo y lima. Cubierta con crema agria y tiras de tortilla.",
    descAr: "فاصوليا سوداء معلبة تتحول إلى حساء غني مدخن بالكمون والثوم والليمون. تزين بالكريمة الحامضة وشرائح التورتيا.",
  },

  // ===== FITNESS & HEALTHY (健身减脂餐) =====
  {
    id: "grilled-salmon-bowl",
    name: "Grilled Salmon Power Bowl",
    nameEs: "Bol Energético de Salmón",
    nameAr: "طبق السلمون المشوي",
    category: "fitness-diet",
    emoji: "🍣",
    calories: "450-520 kcal",
    desc: "Grilled Atlantic salmon, quinoa, roasted sweet potatoes, avocado, edamame, and lemon-tahini dressing.",
    descEs: "Salmón Atlántico a la parrilla, quinoa, batatas asadas, aguacate, edamame y aderezo de limón y tahini.",
    descAr: "سلمون أطلسي مشوي وكينوا وبطاطا حلوة محمصة وأفوكادو وإدامامي وصلصة ليمون وطحينة.",
  },
  {
    id: "chicken-quinoa-salad",
    name: "Grilled Chicken Quinoa Salad",
    nameEs: "Ensalada de Pollo y Quinoa",
    nameAr: "سلطة الدجاج والكينوا",
    category: "fitness-diet",
    emoji: "🥗",
    calories: "380-450 kcal",
    desc: "Herb-grilled chicken breast over quinoa, spinach, cucumber, cherry tomatoes, avocado, and light vinaigrette.",
    descEs: "Pechuga de pollo a la parrilla con hierbas sobre quinoa, espinacas, pepino, tomates cherry, aguacate y vinagreta ligera.",
    descAr: "صدر دجاج مشوي بالأعشاب على كينوا وسبانخ وخيار وطماطم كرزية وأفوكادو مع صلصة خفيفة.",
  },
  {
    id: "mediterranean-bowl",
    name: "Mediterranean Chickpea Bowl",
    nameEs: "Bol Mediterráneo de Garbanzos",
    nameAr: "طبق الحمص المتوسطي",
    category: "fitness-diet",
    emoji: "🫘",
    calories: "350-420 kcal",
    desc: "Warm chickpeas, cucumber, cherry tomatoes, red onion, kalamata olives, feta, and tzatziki over mixed greens.",
    descEs: "Garbanzos calientes, pepino, tomates cherry, cebolla roja, aceitunas kalamata, feta y tzatziki sobre verduras mixtas.",
    descAr: "حمص دافئ وخيار وطماطم كرزية وبصل أحمر وزيتون كالاماتا وجبن فيتا وتزاتزيكي على خضروات مشكلة.",
  },
  {
    id: "turkey-lettuce-wraps",
    name: "Asian Turkey Lettuce Wraps",
    nameEs: "Wraps de Lechuga con Pavo",
    nameAr: "لفائف الخس بالديك الرومي",
    category: "fitness-diet",
    emoji: "🥬",
    calories: "280-350 kcal",
    desc: "Seasoned ground turkey in butter lettuce cups with shredded carrots, green onion, and hoisin drizzle. Low-carb and fresh.",
    descEs: "Pavo molido sazonado en tazas de lechuga mantequilla con zanahoria rallada, cebollín y salsa hoisin. Bajo en carbohidratos.",
    descAr: "ديك رومي مفروم متبل في أكواب خس الزبدة مع جزر مبشور وبصل أخضر وصلصة هويسين. منخفض الكربوهيدرات.",
  },
  {
    id: "protein-buddha-bowl",
    name: "Protein Buddha Bowl",
    nameEs: "Bowl Buda de Proteínas",
    nameAr: "طبق بوذا البروتيني",
    category: "fitness-diet",
    emoji: "🥙",
    calories: "420-500 kcal",
    desc: "Roasted tofu (or grilled chicken), brown rice, kale, sweet potato, pickled red cabbage, and miso-tahini dressing.",
    descEs: "Tofu asado (o pollo a la parrilla), arroz integral, col rizada, batata, col roja encurtida y aderezo de miso y tahini.",
    descAr: "توفو محمص (أو دجاج مشوي) وأرز بني وكرنب وبطاطا حلوة وملفوف أحمر مخلل وصلصة ميسو وطحينة.",
  },
  {
    id: "egg-white-omelette",
    name: "Egg White Veggie Omelette",
    nameEs: "Omelette de Claras con Verduras",
    nameAr: "عجة بياض البيض بالخضار",
    category: "fitness-diet",
    emoji: "🥚",
    calories: "180-250 kcal",
    desc: "Fluffy egg white omelette stuffed with spinach, mushrooms, bell peppers, and a sprinkle of low-fat feta.",
    descEs: "Omelette esponjoso de claras de huevo relleno de espinacas, champiñones, pimientos y un toque de queso feta bajo en grasa.",
    descAr: "عجة بياض بيض هشة محشوة بالسبانخ والفطر والفلفل الحلو مع رشة جبن فيتا قليل الدسم.",
  },
  {
    id: "grilled-chicken-avocado-salad",
    name: "Grilled Chicken & Avocado Salad",
    nameEs: "Ensalada de Pollo y Aguacate",
    nameAr: "سلطة الدجاج المشوي والأفوكادو",
    category: "fitness-diet",
    emoji: "🥑",
    calories: "350-420 kcal",
    desc: "Grilled chicken breast, fresh avocado, mixed greens, cherry tomatoes, corn, black beans, and cilantro-lime dressing.",
    descEs: "Pechuga de pollo a la parrilla, aguacate fresco, verduras mixtas, tomates cherry, elote, frijoles negros y aderezo de cilantro y lima.",
    descAr: "صدر دجاج مشوي وأفوكادو طازج وخضروات مشكلة وطماطم كرزية وذرة وفاصوليا سوداء وصلصة كزبرة ولايم.",
  },
  {
    id: "shrimp-zucchini-noodles",
    name: "Garlic Shrimp Zucchini Noodles",
    nameEs: "Fideos de Calabacín con Camarones",
    nameAr: "نودلز الكوسا بالروبيان",
    category: "fitness-diet",
    emoji: "🍤",
    calories: "280-350 kcal",
    desc: "Spiralized zucchini noodles sautéed with garlic shrimp, cherry tomatoes, and fresh basil. Low-carb pasta alternative.",
    descEs: "Fideos de calabacín salteados con camarones al ajo, tomates cherry y albahaca fresca. Alternativa baja en carbohidratos.",
    descAr: "نودلز كوسا مقلية مع روبيان بالثوم وطماطم كرزية وريحان طازج. بديل معكرونة منخفض الكربوهيدرات.",
  },
  {
    id: "tuna-poke-bowl",
    name: "Spicy Tuna Poke Bowl",
    nameEs: "Bol de Poke de Atún Picante",
    nameAr: "طبق بوكي التونة الحار",
    category: "fitness-diet",
    emoji: "🍚",
    calories: "420-500 kcal",
    desc: "Sushi-grade ahi tuna, brown rice, cucumber, edamame, seaweed salad, avocado, and spicy mayo.",
    descEs: "Atún ahi grado sushi, arroz integral, pepino, edamame, ensalada de algas, aguacate y mayonesa picante.",
    descAr: "تونة آهي بدرجة سوشي وأرز بني وخيار وإدامامي وسلطة أعشاب بحرية وأفوكادو ومايونيز حار.",
  },
  {
    id: "spinach-feta-wrap",
    name: "Spinach & Feta Egg White Wrap",
    nameEs: "Wrap de Espinacas y Feta con Claras",
    nameAr: "لفافة سبانخ وفيتا ببياض البيض",
    category: "fitness-diet",
    emoji: "🌯",
    calories: "280-340 kcal",
    desc: "Egg whites scrambled with fresh spinach and feta, wrapped in a whole wheat tortilla. High-protein breakfast-for-lunch.",
    descEs: "Claras de huevo revueltas con espinacas frescas y queso feta, envueltas en tortilla integral. Desayuno-almuerzo alto en proteínas.",
    descAr: "بياض بيض مخفوق مع سبانخ طازجة وجبن فيتا، ملفوف في خبز تورتيا قمح كامل. فطور-غداء عالي البروتين.",
  },
  {
    id: "lentil-sweet-potato-stew",
    name: "Lentil & Sweet Potato Stew",
    nameEs: "Guiso de Lentejas y Batata",
    nameAr: "يخنة العدس والبطاطا الحلوة",
    category: "fitness-diet",
    emoji: "🍲",
    calories: "320-400 kcal",
    desc: "Hearty vegan stew with red lentils, sweet potatoes, kale, coconut milk, and warm spices. High fiber, high protein.",
    descEs: "Guiso vegano abundante con lentejas rojas, batatas, col rizada, leche de coco y especias cálidas. Alto en fibra y proteína.",
    descAr: "يخنة نباتية شهية بالعدس الأحمر والبطاطا الحلوة والكرنب وحليب جوز الهند والتوابل الدافئة. غنية بالألياف والبروتين.",
  },
  {
    id: "cottage-cheese-bowl",
    name: "Cottage Cheese Power Bowl",
    nameEs: "Bol Energético de Requesón",
    nameAr: "طبق جبن القريش",
    category: "fitness-diet",
    emoji: "🫐",
    calories: "250-320 kcal",
    desc: "Creamy cottage cheese topped with fresh berries, sliced banana, granola, chia seeds, and a drizzle of honey.",
    descEs: "Requesón cremoso con frutos rojos frescos, plátano en rodajas, granola, semillas de chía y un chorrito de miel.",
    descAr: "جبن قريش كريمي مع توت طازج وشرائح موز وغرانولا وبذور شيا وقليل من العسل.",
  },
  {
    id: "greek-yogurt-grilled-chicken",
    name: "Greek Yogurt Marinated Chicken",
    nameEs: "Pollo Marinado en Yogur Griego",
    nameAr: "دجاج متبل بالزبادي اليوناني",
    category: "fitness-diet",
    emoji: "🍗",
    calories: "320-400 kcal",
    desc: "Chicken breast marinated in Greek yogurt, lemon, garlic, and herbs, grilled to juicy perfection. Served with cucumber salad.",
    descEs: "Pechuga de pollo marinada en yogur griego, limón, ajo y hierbas, asada hasta quedar jugosa. Servida con ensalada de pepino.",
    descAr: "صدر دجاج متبل بالزبادي اليوناني والليمون والثوم والأعشاب، مشوي حتى العصارة. يقدم مع سلطة الخيار.",
  },
  {
    id: "smoothie-bowl",
    name: "Acai Smoothie Bowl",
    nameEs: "Bol de Smoothie de Acai",
    nameAr: "طبق سموذي أكاي",
    category: "fitness-diet",
    emoji: "🍓",
    calories: "300-380 kcal",
    desc: "Blended acai with banana and mixed berries, topped with granola, coconut flakes, sliced fruit, and a drizzle of almond butter.",
    descEs: "Acai mezclado con plátano y frutos rojos, cubierto con granola, hojuelas de coco, fruta en rodajas y mantequilla de almendras.",
    descAr: "أكاي ممزوج بالموز والتوت المشكل، مع غرانولا ورقائق جوز الهند وفاكهة مقطعة وزبدة اللوز.",
  },

  // ===== COMFORT FOOD (解馋正餐) =====
  {
    id: "margherita-pizza",
    name: "Margherita Pizza",
    nameEs: "Pizza Margarita",
    nameAr: "بيتزا مارغريتا",
    category: "comfort-food",
    emoji: "🍕",
    calories: "700-900 kcal",
    desc: "Thin-crust Neapolitan pizza with San Marzano tomato sauce, fresh mozzarella, basil, and extra virgin olive oil.",
    descEs: "Pizza napolitana de corteza fina con salsa de tomate San Marzano, mozzarella fresca, albahaca y aceite de oliva virgen extra.",
    descAr: "بيتزا نابولية بقشرة رقيقة مع صلصة طماطم سان مارزانو وجبن موزاريلا طازج وريحان وزيت زيتون بكر.",
  },
  {
    id: "bacon-cheeseburger",
    name: "Bacon Cheeseburger",
    nameEs: "Hamburguesa con Queso y Tocino",
    nameAr: "برغر بالجبن ولحم الخنزير المقدد",
    category: "comfort-food",
    emoji: "🍔",
    calories: "750-950 kcal",
    desc: "Juicy beef patty, crispy bacon, melted cheddar, lettuce, tomato, pickles, and special sauce on a brioche bun.",
    descEs: "Jugosa hamburguesa de res, tocino crujiente, queso cheddar derretido, lechuga, tomate, pepinillos y salsa especial en pan brioche.",
    descAr: "قرص لحم بقري طري ولحم مقدد مقرمش وجبن شيدر مذاب وخس وطماطم ومخلل وصلصة خاصة على خبز بريوش.",
  },
  {
    id: "chicken-alfredo",
    name: "Creamy Chicken Alfredo",
    nameEs: "Pollo Alfredo Cremoso",
    nameAr: "دجاج ألفريدو الكريمي",
    category: "comfort-food",
    emoji: "🍝",
    calories: "700-850 kcal",
    desc: "Fettuccine in a rich garlic-parmesan cream sauce with tender grilled chicken. Classic Italian-American indulgence.",
    descEs: "Fettuccine en una rica salsa cremosa de ajo y parmesano con tierno pollo a la parrilla. Un clásico italoamericano.",
    descAr: "فيتوتشيني في صلصة كريمة الثوم والبارميزان الغنية مع دجاج مشوي طري. طبق إيطالي أمريكي كلاسيكي.",
  },
  {
    id: "fish-and-chips",
    name: "Fish & Chips",
    nameEs: "Pescado Rebozado con Papas Fritas",
    nameAr: "سمك وبطاطس مقلية",
    category: "comfort-food",
    emoji: "🐟",
    calories: "650-800 kcal",
    desc: "Beer-battered cod deep-fried golden, served with thick-cut chips, mushy peas, tartar sauce, and malt vinegar.",
    descEs: "Bacalao rebozado en cerveza frito hasta dorar, servido con papas gruesas, puré de guisantes, salsa tártara y vinagre de malta.",
    descAr: "سمك القد المغطى بعجينة البيرة والمقلي حتى يصبح ذهبياً، يقدم مع بطاطس مقلية سميكة وبازلاء مهروسة وصلصة التارتار وخل الشعير.",
  },
  {
    id: "bbq-ribs",
    name: "Smoky BBQ Baby Back Ribs",
    nameEs: "Costillas BBQ Ahumadas",
    nameAr: "أضلاع BBQ مدخنة",
    category: "comfort-food",
    emoji: "🍖",
    calories: "800-1000 kcal",
    desc: "Slow-cooked pork ribs with smoky BBQ glaze, fall-off-the-bone tender. Served with coleslaw and cornbread.",
    descEs: "Costillas de cerdo cocinadas lentamente con glaseado BBQ ahumado. Servidas con ensalada de col y pan de elote.",
    descAr: "أضلاع لحم خنزير مطهوة ببطء مع طلاء باربيكيو مدخن، طرية لدرجة السقوط من العظم. تقدم مع سلطة الملفوف وخبز الذرة.",
  },
  {
    id: "mac-and-cheese-deluxe",
    name: "Truffle Mac & Cheese",
    nameEs: "Macarrones con Queso y Trufa",
    nameAr: "معكرونة بالجبن والكمأة",
    category: "comfort-food",
    emoji: "🧀",
    calories: "650-800 kcal",
    desc: "Elbow macaroni in a decadent three-cheese sauce (gruyère, cheddar, parmesan) with truffle oil and crispy panko crust.",
    descEs: "Macarrones en una salsa decadente de tres quesos (gruyère, cheddar, parmesano) con aceite de trufa y corteza crujiente de panko.",
    descAr: "معكرونة في صلصة ثلاثة أجبان فاخرة (غرويير وشيدر وبارميزان) مع زيت الكمأة وقشرة بانكو مقرمشة.",
  },
  {
    id: "chicken-waffles",
    name: "Chicken & Waffles",
    nameEs: "Pollo Frito con Waffles",
    nameAr: "دجاج مقلي مع وافل",
    category: "comfort-food",
    emoji: "🧇",
    calories: "700-900 kcal",
    desc: "Crispy southern-fried chicken on a fluffy Belgian waffle, drizzled with maple syrup and a dash of hot sauce.",
    descEs: "Pollo frito sureño crujiente sobre un waffle belga esponjoso, con jarabe de arce y un toque de salsa picante.",
    descAr: "دجاج مقلي جنوبي مقرمش على وافل بلجيكي هش، مع شراب القيقب وقليل من الصلصة الحارة.",
  },
  {
    id: "philly-cheesesteak",
    name: "Philly Cheesesteak",
    nameEs: "Cheesesteak de Filadelfia",
    nameAr: "فيللي تشيزستيك",
    category: "comfort-food",
    emoji: "🥩",
    calories: "650-800 kcal",
    desc: "Thinly sliced ribeye steak, grilled onions, bell peppers, and melty provolone cheese on a hoagie roll.",
    descEs: "Filete de ribeye en láminas finas, cebollas asadas, pimientos y queso provolone derretido en un pan hoagie.",
    descAr: "شرائح رقيقة من لحم الريب آي والبصل المشوي والفلفل الحلو وجبن بروفولون المذاب على خبز هواغي.",
  },
  {
    id: "loaded-nachos",
    name: "Loaded Nachos Supreme",
    nameEs: "Nachos Supremos Cargados",
    nameAr: "ناتشوز سوبريم محمل",
    category: "comfort-food",
    emoji: "🧀",
    calories: "750-950 kcal",
    desc: "Crispy tortilla chips piled high with seasoned beef, melted cheese, jalapeños, guacamole, sour cream, and pico de gallo.",
    descEs: "Totopos crujientes cargados con carne sazonada, queso derretido, jalapeños, guacamole, crema agria y pico de gallo.",
    descAr: "رقائق تورتيا مقرمشة مغطاة بلحم بقري متبل وجبن مذاب وهالبينو وغواكامولي وكريمة حامضة وبيكو دي غايو.",
  },
  {
    id: "lobster-roll",
    name: "Buttery Lobster Roll",
    nameEs: "Roll de Langosta con Mantequilla",
    nameAr: "لفة الكركند بالزبدة",
    category: "comfort-food",
    emoji: "🦞",
    calories: "500-650 kcal",
    desc: "Chilled lobster meat tossed in lemon butter on a toasted split-top brioche bun. New England summer classic.",
    descEs: "Carne de langosta fría mezclada con mantequilla de limón en un pan brioche tostado. Clásico de verano de Nueva Inglaterra.",
    descAr: "لحم كركند بارد مخلوط بزبدة الليمون على خبز بريوش محمص. طبق صيفي كلاسيكي من نيو إنجلاند.",
  },
  {
    id: "chicken-parmesan",
    name: "Chicken Parmesan",
    nameEs: "Pollo a la Parmesana",
    nameAr: "دجاج بارميزان",
    category: "comfort-food",
    emoji: "🍗",
    calories: "650-800 kcal",
    desc: "Breaded chicken cutlet smothered in marinara and melted mozzarella-parmesan, served over spaghetti. Italian-American favorite.",
    descEs: "Chuleta de pollo empanizada cubierta de marinara y mozzarella-parmesano derretido, servida sobre espaguetis. Favorito italoamericano.",
    descAr: "صدر دجاج مغطى بالبقسماط ومغطى بصلصة المارينارا وجبن الموزاريلا والبارميزان المذاب، يقدم فوق السباغيتي.",
  },
  {
    id: "pulled-pork-sandwich",
    name: "Pulled Pork Sandwich",
    nameEs: "Sándwich de Cerdo Desmenuzado",
    nameAr: "ساندويتش لحم الخنزير المسحوب",
    category: "comfort-food",
    emoji: "🥪",
    calories: "600-750 kcal",
    desc: "Slow-smoked pulled pork in tangy BBQ sauce, piled on a brioche bun with coleslaw and pickles. Southern BBQ classic.",
    descEs: "Cerdo desmenuzado ahumado lentamente en salsa BBQ, servido en pan brioche con ensalada de col y pepinillos. Clásico sureño.",
    descAr: "لحم خنزير مسحوب مدخن ببطء في صلصة باربيكيو، مكدس على خبز بريوش مع سلطة الملفوف والمخلل. طبق جنوبي كلاسيكي.",
  },
  {
    id: "beef-lasagna",
    name: "Classic Beef Lasagna",
    nameEs: "Lasaña Clásica de Carne",
    nameAr: "لازانيا اللحم الكلاسيكية",
    category: "comfort-food",
    emoji: "🍝",
    calories: "650-800 kcal",
    desc: "Layers of pasta, rich beef ragu, creamy ricotta-bechamel, and mozzarella baked to bubbly perfection.",
    descEs: "Capas de pasta, rico ragú de carne, cremosa bechamel de ricotta y mozzarella horneadas a la perfección.",
    descAr: "طبقات من المعكرونة وراغو اللحم البقري الغني وصلصة الريكوتا البشاميل الكريمية وجبن الموزاريلا مخبوزة حتى الكمال.",
  },
  {
    id: "buffalo-wings",
    name: "Buffalo Chicken Wings",
    nameEs: "Alitas de Pollo Búfalo",
    nameAr: "أجنحة دجاج بافلو",
    category: "comfort-food",
    emoji: "🍗",
    calories: "600-800 kcal",
    desc: "Crispy chicken wings tossed in spicy buffalo sauce, served with celery sticks and blue cheese dip. Game-day essential.",
    descEs: "Alitas de pollo crujientes bañadas en salsa búfalo picante, servidas con apio y aderezo de queso azul. Esencial para días de partido.",
    descAr: "أجنحة دجاج مقرمشة مغطاة بصلصة بافلو الحارة، تقدم مع أعواد الكرفس وصوص الجبن الأزرق. طبق أساسي ليوم المباراة.",
  },
  {
    id: "chicken-tikka-masala",
    name: "Chicken Tikka Masala",
    nameEs: "Pollo Tikka Masala",
    nameAr: "دجاج تكا ماسالا",
    category: "comfort-food",
    emoji: "🍛",
    calories: "550-700 kcal",
    desc: "Tandoori chicken chunks in a creamy spiced tomato sauce, served with basmati rice and warm naan bread. UK's national dish.",
    descEs: "Trozos de pollo tandoori en una salsa cremosa de tomate especiada, servido con arroz basmati y pan naan caliente.",
    descAr: "قطع دجاج تندوري في صلصة طماطم كريمية متبلة، تقدم مع أرز بسمتي وخبز نان دافئ. الطبق الوطني البريطاني.",
  },
];
