export type Region = "north-america" | "europe" | "middle-east" | "latin-america";

export interface FoodItem {
  id: string;
  name: string;
  nameEs: string;
  nameAr: string;
  category: "quick-lunch" | "budget-meals" | "fitness-diet" | "comfort-food";
  regions: Region[];
  emoji: string;
  calories: string;
  desc: string;
  descEs: string;
  descAr: string;
}

export interface FoodCategory {
  id: FoodItem["category"];
  name: string;
  nameEs: string;
  nameAr: string;
  icon: string;
  color: string;
}

export const regions: { id: Region; name: string; nameEs: string; nameAr: string }[] = [
  { id: "north-america", name: "North America", nameEs: "Norteamérica", nameAr: "أمريكا الشمالية" },
  { id: "europe", name: "Europe", nameEs: "Europa", nameAr: "أوروبا" },
  { id: "middle-east", name: "Middle East", nameEs: "Oriente Medio", nameAr: "الشرق الأوسط" },
  { id: "latin-america", name: "Latin America", nameEs: "Latinoamérica", nameAr: "أمريكا اللاتينية" },
];

export function detectRegionByCountry(countryCode: string): Region {
  const eu = ["GB","DE","FR","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IE","PT","PL","CZ","GR","HU","RO","SK","HR","SI","LT","LV","EE","LU","MT","IS"];
  const me = ["SA","AE","QA","KW","BH","OM","JO","LB","EG","IQ","SY","YE","PS","MA","DZ","TN","LY","TR","IR","PK","AF"];
  const la = ["MX","BR","AR","CO","PE","CL","VE","EC","DO","GT","CR","PA","UY","BO","PY","SV","HN","NI","CU","PR"];
  if (eu.includes(countryCode)) return "europe";
  if (me.includes(countryCode)) return "middle-east";
  if (la.includes(countryCode)) return "latin-america";
  return "north-america";
}


export const foodCategories: FoodCategory[] = [
  {
    id: "quick-lunch",
    name: "Quick Office Lunch",
    nameEs: "Almuerzo Rápido de Oficina",
    nameAr: "غداء مكتب سريع",
    icon: "🥪",
    color: "bg-amber-50 border-amber-200 text-amber-800 dark:bg-amber-950/30 dark:border-amber-700 dark:text-amber-300",
  },
  {
    id: "budget-meals",
    name: "Budget-Friendly Bites",
    nameEs: "Bocados Económicos",
    nameAr: "وجبات اقتصادية",
    icon: "🍝",
    color: "bg-green-50 border-green-200 text-green-800 dark:bg-green-950/30 dark:border-green-700 dark:text-green-300",
  },
  {
    id: "fitness-diet",
    name: "Low-Cal Healthy Picks",
    nameEs: "Opciones Saludables Bajas en Calorías",
    nameAr: "خيارات صحية منخفضة السعرات",
    icon: "🥗",
    color: "bg-emerald-50 border-emerald-200 text-emerald-800 dark:bg-emerald-950/30 dark:border-emerald-700 dark:text-emerald-300",
  },
  {
    id: "comfort-food",
    name: "Comfort Food",
    nameEs: "Comida Reconfortante",
    nameAr: "طعام مريح",
    icon: "🍕",
    color: "bg-rose-50 border-rose-200 text-rose-800 dark:bg-rose-950/30 dark:border-rose-700 dark:text-rose-300",
  },
];

export const foodItems: FoodItem[] = [
  // ===== QUICK & EASY LUNCH (上班族简餐) =====
  {
    id: "turkey-club-sandwich",
    name: "Turkey Club Sandwich",
    nameEs: "Sándwich Club de Pavo",
    nameAr: "ساندويتش الديك الرومي",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥪",
    calories: "450-550 kcal",
    desc: "Triple-decker with roasted turkey, crispy bacon, lettuce, tomato, and mayo on toasted bread.",
    descEs: "Sándwich triple con pavo asado, tocino crujiente, lechuga, tomate y mayonesa en pan tostado.",
    descAr: "ساندويتش ثلاثي الطبقات مع ديك رومي مشوي ولحم مقدد مقرمش وخس وطماطم ومايونيز على خبز محمص.",
  },
  {
    id: "caesar-salad-wrap",
    name: "Caesar Salad Wrap",
    nameEs: "Wrap de Ensalada César",
    nameAr: "لفافة سلطة سيزر",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🌯",
    calories: "380-450 kcal",
    desc: "Grilled chicken, romaine lettuce, parmesan, croutons, and Caesar dressing in a flour tortilla.",
    descEs: "Pollo a la parrilla, lechuga romana, parmesano, crutones y aderezo César en tortilla de harina.",
    descAr: "دجاج مشوي وخس روماني وبارميزان وخبز محمص وصلصة سيزر في خبز تورتيا.",
  },
  {
    id: "grilled-chicken-panini",
    name: "Grilled Chicken Panini",
    nameEs: "Panini de Pollo a la Parrilla",
    nameAr: "بانيني الدجاج المشوي",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥖",
    calories: "480-550 kcal",
    desc: "Pressed Italian sandwich with grilled chicken, mozzarella, sun-dried tomatoes, and pesto aioli.",
    descEs: "Sándwich italiano prensado con pollo a la parrilla, mozzarella, tomates secos y alioli de pesto.",
    descAr: "ساندويتش إيطالي مضغوط مع دجاج مشوي وجبن موزاريلا وطماطم مجففة وأيولي البيستو.",
  },
  {
    id: "quiche-lorraine",
    name: "Quiche Lorraine",
    nameEs: "Quiche Lorraine",
    nameAr: "كيش لورين",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥧",
    calories: "420-500 kcal",
    desc: "Classic French savory tart with bacon, Gruyère cheese, and egg custard in a buttery crust.",
    descEs: "Clásica tarta salada francesa con tocino, queso Gruyère y crema de huevo en corteza de mantequilla.",
    descAr: "تارت فرنسي كلاسيكي بالبيكون وجبن غرويير وكاسترد البيض في قشرة زبدية.",
  },
  {
    id: "caprese-panini",
    name: "Caprese Panini",
    nameEs: "Panini Caprese",
    nameAr: "بانيني كابريزي",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥖",
    calories: "380-430 kcal",
    desc: "Fresh mozzarella, sliced tomatoes, basil leaves, and balsamic glaze pressed between ciabatta.",
    descEs: "Mozzarella fresca, tomates en rodajas, hojas de albahaca y glaseado balsámico prensado en ciabatta.",
    descAr: "جبن موزاريلا طازج وشرائح طماطم وأوراق ريحان وصوص بلسمي مضغوط بين خبز سياباتا.",
  },
  {
    id: "chicken-avocado-toast",
    name: "Chicken Avocado Toast",
    nameEs: "Tostada de Pollo y Aguacate",
    nameAr: "توست الدجاج والأفوكادو",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥑",
    calories: "350-420 kcal",
    desc: "Sourdough toast topped with smashed avocado, sliced grilled chicken, cherry tomatoes, and everything bagel seasoning.",
    descEs: "Tostada de masa madre con puré de aguacate, pollo a la parrilla en rodajas, tomates cherry y condimento everything bagel.",
    descAr: "توست العجين المخمر مع أفوكادو مهروس وشرائح دجاج مشوي وطماطم كرزية وبهارات الخبز.",
  },
  {
    id: "tuna-nicoise-bowl",
    name: "Tuna Niçoise Bowl",
    nameEs: "Bol de Atún Niçoise",
    nameAr: "طبق التونة نيسواز",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥗",
    calories: "400-480 kcal",
    desc: "Seared tuna, boiled eggs, green beans, olives, potatoes, and mixed greens with Dijon vinaigrette.",
    descEs: "Atún sellado, huevos duros, judías verdes, aceitunas, papas y verduras mixtas con vinagreta de Dijon.",
    descAr: "تونة مشوية وبيض مسلوق وفاصوليا خضراء وزيتون وبطاطس وخضروات مشكلة مع صلصة ديجون.",
  },
  {
    id: "italian-sub",
    name: "Italian Sub",
    nameEs: "Sándwich Italiano",
    nameAr: "ساندويتش إيطالي",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥖",
    calories: "520-620 kcal",
    desc: "Loaded sub roll with salami, ham, provolone, lettuce, tomato, onion, pepperoncini, and Italian dressing.",
    descEs: "Panecillo relleno con salami, jamón, provolone, lechuga, tomate, cebolla, pepperoncini y aderezo italiano.",
    descAr: "خبز محشو بالسجق المجفف ولحم الخنزير وجبن بروفولون وخس وطماطم وبصل وفلفل مخلل وصوص إيطالي.",
  },
  {
    id: "buffalo-chicken-wrap",
    name: "Buffalo Chicken Wrap",
    nameEs: "Wrap de Pollo Búfalo",
    nameAr: "لفافة دجاج بافلو",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🌯",
    calories: "450-530 kcal",
    desc: "Crispy buffalo chicken tenders, shredded lettuce, diced tomatoes, and ranch dressing wrapped in a warm flour tortilla.",
    descEs: "Tiras de pollo búfalo crujientes, lechuga rallada, tomates en cubitos y aderezo ranch envueltos en una tortilla de harina caliente.",
    descAr: "قطع دجاج بافلو مقرمشة وخس مقطع وطماطم مقطعة وصلصة رانش ملفوفة في خبز تورتيا دافئ.",
  },
  {
    id: "soup-and-salad-combo",
    name: "Soup & Salad Combo",
    nameEs: "Combo de Sopa y Ensalada",
    nameAr: "طبق حساء وسلطة",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🍜",
    calories: "300-450 kcal",
    desc: "Half sandwich or soup of the day paired with a fresh garden salad. Light yet satisfying lunch classic.",
    descEs: "Medio sándwich o sopa del día acompañado de ensalada fresca. Clásico ligero pero satisfactorio.",
    descAr: "نصف ساندويتش أو حساء اليوم مع سلطة طازجة. غداء كلاسيكي خفيف ومشبع.",
  },
  {
    id: "mediterranean-flatbread",
    name: "Mediterranean Flatbread",
    nameEs: "Pan Plano Mediterráneo",
    nameAr: "خبز مسطح متوسطي",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🫓",
    calories: "420-500 kcal",
    desc: "Warm flatbread topped with hummus, roasted red peppers, feta, olives, arugula, and lemon-herb drizzle.",
    descEs: "Pan plano caliente con hummus, pimientos rojos asados, feta, aceitunas, rúcula y aderezo de limón y hierbas.",
    descAr: "خبز مسطح دافئ مع حمص وفلفل أحمر محمص وجبن فيتا وزيتون وجرجير وصوص ليمون بالأعشاب.",
  },
  {
    id: "blt-sandwich",
    name: "Classic BLT Sandwich",
    nameEs: "Sándwich BLT Clásico",
    nameAr: "ساندويتش بي إل تي كلاسيكي",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥓",
    calories: "380-480 kcal",
    desc: "Crispy bacon, fresh lettuce, and juicy tomato slices layered with mayo on toasted sourdough. Simple, timeless, perfect.",
    descEs: "Tocino crujiente, lechuga fresca y jugosas rodajas de tomate con mayonesa en pan de masa madre tostado. Simple y perfecto.",
    descAr: "لحم مقدد مقرمش وخس طازج وشرائح طماطم غنية بالعصير مع مايونيز على خبز العجين المخمر المحمص. بسيط ومثالي.",
  },
  {
    id: "bagel-with-lox",
    name: "Bagel with Lox",
    nameEs: "Bagel con Salmón",
    nameAr: "خبز بيغل مع السلمون",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🥯",
    calories: "380-480 kcal",
    desc: "Toasted bagel with cream cheese, smoked salmon, capers, red onion, and fresh dill. NYC deli classic.",
    descEs: "Bagel tostado con queso crema, salmón ahumado, alcaparras, cebolla roja y eneldo fresco. Clásico de Nueva York.",
    descAr: "خبز بيغل محمص مع جبن كريمي وسلمون مدخن وكبر وبصل أحمر وشبت طازج. طبق نيويوركي كلاسيكي.",
  },
  {
    id: "greek-salad-pita",
    name: "Greek Salad Pita",
    nameEs: "Pita de Ensalada Griega",
    nameAr: "بيتا سلطة يونانية",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🫓",
    calories: "340-420 kcal",
    desc: "Warm pita stuffed with cucumber, tomato, red onion, kalamata olives, feta, and Greek yogurt dressing.",
    descEs: "Pita caliente rellena de pepino, tomate, cebolla roja, aceitunas kalamata, feta y aderezo de yogur griego.",
    descAr: "خبز بيتا دافئ محشو بالخيار والطماطم والبصل الأحمر وزيتون كالاماتا وجبن فيتا وصلصة زبادي يونانية.",
  },
  {
    id: "bbq-chicken-quesadilla",
    name: "BBQ Chicken Quesadilla",
    nameEs: "Quesadilla de Pollo BBQ",
    nameAr: "كويساديا الدجاج بالباربيكيو",
    category: "quick-lunch",
    regions: ["north-america"],
    emoji: "🫔",
    calories: "480-580 kcal",
    desc: "Crispy flour tortilla filled with BBQ shredded chicken, cheddar-jack cheese, red onion, and cilantro.",
    descEs: "Tortilla de harina crujiente rellena de pollo desmenuzado BBQ, queso cheddar-jack, cebolla roja y cilantro.",
    descAr: "تورتيا طحين مقرمشة محشوة بالدجاج المبهر بصلصة الباربيكيو وجبن شيدر وبصل أحمر وكزبرة.",
  },

  // ===== BUDGET-FRIENDLY BITES (学生平价餐) =====
  {
    id: "classic-spaghetti",
    name: "Classic Spaghetti Bolognese",
    nameEs: "Espaguetis a la Boloñesa",
    nameAr: "سباغيتي بولونيز",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍝",
    calories: "550-650 kcal",
    desc: "Hearty pasta with rich beef-tomato sauce, garlic, onions, and herbs. The ultimate budget comfort staple.",
    descEs: "Pasta abundante con rica salsa de carne de res y tomate, ajo, cebolla y hierbas. El básico económico definitivo.",
    descAr: "معكرونة شهية مع صلصة لحم البقر والطماطم الغنية والثوم والبصل والأعشاب. الطبق الاقتصادي المثالي.",
  },
  {
    id: "mac-and-cheese",
    name: "Mac & Cheese",
    nameEs: "Macarrones con Queso",
    nameAr: "معكرونة بالجبن",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🧀",
    calories: "450-550 kcal",
    desc: "Creamy, cheesy elbow macaroni with a crispy breadcrumb topping. Baked golden and bubbly.",
    descEs: "Macarrones cremosos con queso y cobertura crujiente de pan rallado. Horneados dorados y burbujeantes.",
    descAr: "معكرونة كريمية بالجبن مع طبقة مقرمشة من فتات الخبز. مخبوزة حتى تصبح ذهبية وفقاعية.",
  },
  {
    id: "ramen-upgrade",
    name: "Upgraded Instant Ramen",
    nameEs: "Ramen Instantáneo Mejorado",
    nameAr: "رامين سريع التحضير مطور",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍜",
    calories: "400-500 kcal",
    desc: "Instant ramen elevated with soft-boiled egg, green onions, corn, nori, and a drizzle of sesame oil.",
    descEs: "Ramen instantáneo mejorado con huevo tibio, cebollines, elote, nori y un chorrito de aceite de sésamo.",
    descAr: "رامين سريع التحضير مطور مع بيض نصف مسلوق وبصل أخضر وذرة ونوري وقليل من زيت السمسم.",
  },
  {
    id: "bean-cheese-burrito",
    name: "Bean & Cheese Burrito",
    nameEs: "Burrito de Frijoles y Queso",
    nameAr: "بوريتو الفاصوليا والجبن",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🌯",
    calories: "480-580 kcal",
    desc: "Large flour tortilla stuffed with refried beans, melted cheddar, rice, and salsa. Filling and cheap.",
    descEs: "Tortilla de harina grande rellena de frijoles refritos, queso cheddar derretido, arroz y salsa. Sacia y es barato.",
    descAr: "تورتيا طحين كبيرة محشوة بالفاصوليا المقلية وجبن شيدر مذاب وأرز وصلصة. مشبعة ورخيصة.",
  },
  {
    id: "tuna-melt-sandwich",
    name: "Tuna Melt Sandwich",
    nameEs: "Sándwich de Atún Fundido",
    nameAr: "ساندويتش التونة المذابة",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🥪",
    calories: "400-500 kcal",
    desc: "Classic diner-style open-faced tuna salad with melted cheddar on toasted bread. Made with canned tuna.",
    descEs: "Clásico sándwich abierto de ensalada de atún estilo diner con queso cheddar derretido en pan tostado.",
    descAr: "ساندويتش تونة كلاسيكي مفتوح على طراز المطاعم مع جبن شيدر مذاب على خبز محمص. مصنوع من التونة المعلبة.",
  },
  {
    id: "tuna-jacket-potato",
    name: "Tuna Mayo Jacket Potato",
    nameEs: "Papa Asada con Atún y Mayonesa",
    nameAr: "بطاطس مشوية بالتونة والمايونيز",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🥔",
    calories: "380-480 kcal",
    desc: "Fluffy baked potato split open and loaded with tuna mayo, sweetcorn, and a sprinkle of cheddar. British lunch staple.",
    descEs: "Papa al horno esponjosa abierta y cargada con atún, mayonesa, elote dulce y queso cheddar. Clásico británico.",
    descAr: "بطاطس مخبوزة هشة مشقوقة ومحملة بالتونة والمايونيز والذرة الحلوة مع رشة جبن شيدر. طبق غداء بريطاني أساسي.",
  },
  {
    id: "grilled-cheese-soup",
    name: "Grilled Cheese + Tomato Soup",
    nameEs: "Sándwich de Queso Fundido + Sopa de Tomate",
    nameAr: "ساندويتش جبن مشوي + حساء طماطم",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🥫",
    calories: "420-520 kcal",
    desc: "Golden buttery grilled cheese paired with warm tomato soup for dipping. The ultimate budget comfort duo.",
    descEs: "Sándwich de queso dorado y mantecoso combinado con sopa de tomate caliente para mojar.",
    descAr: "ساندويتش جبن ذهبي بالزبدة مع حساء طماطم دافئ للتغميس. الثنائي المريح الاقتصادي المثالي.",
  },
  {
    id: "chicken-rice-bowl",
    name: "Chicken Rice Bowl",
    nameEs: "Bol de Arroz con Pollo",
    nameAr: "طبق أرز بالدجاج",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍚",
    calories: "450-550 kcal",
    desc: "Simple seasoned chicken thighs over steamed rice with steamed broccoli and teriyaki drizzle.",
    descEs: "Muslos de pollo sazonados sobre arroz al vapor con brócoli y salsa teriyaki.",
    descAr: "أفخاذ دجاج متبلة على أرز مطهو بالبخار مع بروكلي وصلصة ترياكي.",
  },
  {
    id: "loaded-baked-potato",
    name: "Loaded Baked Potato",
    nameEs: "Papa al Horno Cargada",
    nameAr: "بطاطس مخبوزة محملة",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🥔",
    calories: "400-500 kcal",
    desc: "Fluffy baked potato fully loaded with sour cream, cheddar, bacon bits, and chives. Hearty and under $3.",
    descEs: "Papa al horno esponjosa completamente cargada con crema agria, queso cheddar, trocitos de tocino y cebollino.",
    descAr: "بطاطس مخبوزة هشة محملة بالكريمة الحامضة وجبن شيدر وقطع لحم مقدد وثوم معمر. مشبعة وأقل من 3 دولارات.",
  },

  {
    id: "sloppy-joes",
    name: "Sloppy Joes",
    nameEs: "Sloppy Joes",
    nameAr: "سلوبي جو",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍔",
    calories: "400-520 kcal",
    desc: "Seasoned ground beef in tangy tomato sauce piled on a soft hamburger bun. Messy, sweet, and totally satisfying.",
    descEs: "Carne molida sazonada en salsa de tomate sobre pan de hamburguesa suave. Desordenado, dulce y muy satisfactorio.",
    descAr: "لحم بقري مفروم متبل في صلصة طماطم منعشة على خبز همبرغر طري. فوضوي وحلو ومرضٍ تماماً.",
  },
  {
    id: "pasta-aglio-olio",
    name: "Spaghetti Aglio e Olio",
    nameEs: "Espaguetis Aglio e Olio",
    nameAr: "سباغيتي أغليو إي أوليو",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍝",
    calories: "350-450 kcal",
    desc: "Simple Italian classic — spaghetti tossed with garlic sautéed in olive oil, red pepper flakes, and parsley. 5 ingredients max.",
    descEs: "Clásico italiano simple: espaguetis mezclados con ajo salteado en aceite de oliva, hojuelas de chile rojo y perejil. Máximo 5 ingredientes.",
    descAr: "طبق إيطالي بسيط كلاسيكي - سباغيتي مقلية بالثوم في زيت الزيتون ورقائق الفلفل الأحمر والبقدونس. 5 مكونات كحد أقصى.",
  },
  {
    id: "creamy-tomato-pasta",
    name: "Creamy Tomato Pasta",
    nameEs: "Pasta Cremosa de Tomate",
    nameAr: "معكرونة بصلصة الطماطم الكريمية",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍝",
    calories: "400-500 kcal",
    desc: "Penne in a velvety tomato-cream sauce with garlic and basil. Ready in 15 minutes from pantry staples. Student classic.",
    descEs: "Penne en una salsa aterciopelada de tomate y crema con ajo y albahaca. Listo en 15 minutos. Clásico estudiantil.",
    descAr: "بيني في صلصة طماطم كريمية مخملية مع الثوم والريحان. جاهز في 15 دقيقة. طبق طلابي كلاسيكي.",
  },
  {
    id: "tuna-pasta-salad",
    name: "Tuna Pasta Salad",
    nameEs: "Ensalada de Pasta con Atún",
    nameAr: "سلطة المعكرونة بالتونة",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🥗",
    calories: "380-480 kcal",
    desc: "Cold rotini pasta with canned tuna, sweet corn, peas, and light mayo. Great for meal-prep, stays fresh for days.",
    descEs: "Pasta rotini fría con atún enlatado, elote dulce, guisantes y mayonesa ligera. Ideal para preparar con anticipación.",
    descAr: "معكرونة روتيني باردة مع تونة معلبة وذرة حلوة وبازلاء ومايونيز خفيف. رائع للتحضير المسبق.",
  },
  {
    id: "cheese-quesadilla",
    name: "Cheese Quesadilla with Salsa",
    nameEs: "Quesadilla de Queso con Salsa",
    nameAr: "كويساديا الجبن مع الصلصة",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🫔",
    calories: "350-450 kcal",
    desc: "Crispy golden tortilla filled with melted cheese blend, served with sour cream and fresh salsa. Ready in 5 minutes.",
    descEs: "Tortilla dorada y crujiente rellena de mezcla de quesos derretidos, con crema agria y salsa fresca. Lista en 5 minutos.",
    descAr: "تورتيا ذهبية مقرمشة محشوة بخليط جبن مذاب، تقدم مع كريمة حامضة وصلصة طازجة. جاهزة في 5 دقائق.",
  },
  {
    id: "pita-pizza",
    name: "Pita Bread Pizza",
    nameEs: "Pizza de Pan Pita",
    nameAr: "بيتزا خبز البيتا",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍕",
    calories: "300-400 kcal",
    desc: "Store-bought pita topped with tomato sauce, shredded mozzarella, and your favorite toppings. Baked in 8 minutes.",
    descEs: "Pan pita comprado cubierto con salsa de tomate, mozzarella rallada y tus ingredientes favoritos. Horneado en 8 minutos.",
    descAr: "خبز بيتا جاهز مغطى بصلصة طماطم وجبن موزاريلا مبشور وإضافاتك المفضلة. يخبز في 8 دقائق.",
  },
  {
    id: "black-bean-soup",
    name: "Hearty Black Bean Soup",
    nameEs: "Sopa de Frijoles Negros",
    nameAr: "حساء الفاصوليا السوداء",
    category: "budget-meals",
    regions: ["north-america"],
    emoji: "🍲",
    calories: "280-380 kcal",
    desc: "Canned black beans transformed into a rich, smoky soup with cumin, garlic, and lime. Top with sour cream and tortilla strips.",
    descEs: "Frijoles negros enlatados transformados en una sopa rica y ahumada con comino, ajo y lima. Cubierta con crema agria y tiras de tortilla.",
    descAr: "فاصوليا سوداء معلبة تتحول إلى حساء غني مدخن بالكمون والثوم والليمون. تزين بالكريمة الحامضة وشرائح التورتيا.",
  },

  
  // ===== EUROPE — Quick Office Lunch =====
  {
    id: "croque-monsieur",
    name: "Croque Monsieur", nameEs: "Croque Monsieur", nameAr: "كروك موسيو",
    category: "quick-lunch", regions: ["europe"], emoji: "🥪", calories: "420-500 kcal",
    desc: "Classic French grilled ham and cheese sandwich with creamy béchamel sauce, Gruyère, and Dijon mustard on crusty bread.",
    descEs: "Clásico sándwich francés de jamón y queso a la parrilla con salsa bechamel cremosa, Gruyère y mostaza de Dijon en pan crujiente.",
    descAr: "ساندويتش فرنسي كلاسيكي بالجبن ولحم الخنزير المشوي مع صلصة البشاميل الكريمية وجبن غرويير وخردل ديجون على خبز مقرمش.",
  },
  {
    id: "ploughmans-lunch",
    name: "Ploughman's Lunch", nameEs: "Almuerzo del Labrador", nameAr: "غداء الفلاح",
    category: "quick-lunch", regions: ["europe"], emoji: "🧀", calories: "480-580 kcal",
    desc: "Traditional English pub lunch: crusty bread, sharp cheddar, Branston pickle, ham, apple, and pickled onions on a wooden board.",
    descEs: "Almuerzo de pub inglés tradicional: pan crujiente, queso cheddar fuerte, pepinillo Branston, jamón, manzana y cebollas encurtidas.",
    descAr: "غداء حانة إنجليزي تقليدي: خبز مقرمش وجبن شيدر حاد ومخلل برانستون ولحم خنزير وتفاح وبصل مخلل على لوح خشبي.",
  },
  {
    id: "spanish-tortilla-pintxo",
    name: "Spanish Tortilla Baguette", nameEs: "Bocadillo de Tortilla Española", nameAr: "ساندويتش تورتيا إسبانية",
    category: "quick-lunch", regions: ["europe"], emoji: "🥖", calories: "380-460 kcal",
    desc: "Warm baguette stuffed with thick wedges of Spanish potato-egg tortilla, alioli, and roasted red peppers. Barcelona-style fast lunch.",
    descEs: "Baguette caliente rellena de gruesos trozos de tortilla española de patata y huevo, alioli y pimientos rojos asados. Almuerzo rápido estilo Barcelona.",
    descAr: "خبز باغيت دافئ محشو بقطع سميكة من التورتيا الإسبانية بالبطاطس والبيض وأيولي وفلفل أحمر محمص. غداء سريع على طريقة برشلونة.",
  },
  {
    id: "gyro-wrap",
    name: "Chicken Gyro Wrap", nameEs: "Wrap de Gyro de Pollo", nameAr: "لفافة جيرو الدجاج",
    category: "quick-lunch", regions: ["europe", "middle-east"], emoji: "🌯", calories: "480-560 kcal",
    desc: "Warm pita wrapped around seasoned grilled chicken, tzatziki, sliced tomatoes, red onion, and crispy fries — Greek street food favorite.",
    descEs: "Pita caliente envuelta con pollo a la parrilla sazonado, tzatziki, tomates en rodajas, cebolla roja y papas fritas crujientes. Favorito de la calle griega.",
    descAr: "خبز بيتا دافئ ملفوف حول دجاج مشوي متبل وتزاتزيكي وشرائح طماطم وبصل أحمر وبطاطس مقلية مقرمشة. طعام شارع يوناني مفضل.",
  },
  {
    id: "italian-panini-prosciutto",
    name: "Prosciutto & Mozzarella Panini", nameEs: "Panini de Prosciutto y Mozzarella", nameAr: "بانيني بروشوتو وموزاريلا",
    category: "quick-lunch", regions: ["europe"], emoji: "🥖", calories: "420-500 kcal",
    desc: "Pressed ciabatta with Parma prosciutto, fresh mozzarella di bufala, ripe tomato, basil leaves, and a drizzle of extra virgin olive oil.",
    descEs: "Ciabatta prensada con prosciutto de Parma, mozzarella fresca de búfala, tomate maduro, hojas de albahaca y aceite de oliva virgen extra.",
    descAr: "خبز سياباتا مضغوط مع بروشوتو بارما وجبن موزاريلا بوفالو طازج وطماطم ناضجة وأوراق ريحان وزيت زيتون بكر ممتاز.",
  },
  {
    id: "british-jacket-potato",
    name: "Cheesy Beans Jacket Potato", nameEs: "Papa Asada con Frijoles y Queso", nameAr: "بطاطس مشوية بالفاصوليا والجبن",
    category: "quick-lunch", regions: ["europe"], emoji: "🥔", calories: "420-520 kcal",
    desc: "Fluffy baked potato loaded with Heinz baked beans, grated mature cheddar, and a knob of butter. British lunch counter staple.",
    descEs: "Papa asada esponjosa cargada con frijoles horneados Heinz, queso cheddar maduro rallado y mantequilla. Básico de los mostradores británicos.",
    descAr: "بطاطس مخبوزة هشة محملة بفاصوليا هاينز المخبوزة وجبن شيدر معتق مبشور وقطعة زبدة. وجبة غداء بريطانية أساسية.",
  },
  {
    id: "currywurst-pommes",
    name: "Currywurst with Fries", nameEs: "Currywurst con Papas", nameAr: "كاريورست مع بطاطس مقلية",
    category: "quick-lunch", regions: ["europe"], emoji: "🌭", calories: "550-650 kcal",
    desc: "Sliced German bratwurst smothered in spicy curry-ketchup sauce, dusted with curry powder, served with crispy fries. Berlin street icon.",
    descEs: "Salchicha bratwurst alemana en rodajas cubierta de salsa picante de curry-ketchup, espolvoreada con curry en polvo, servida con papas fritas.",
    descAr: "نقانق براتورست ألمانية مقطعة مغطاة بصلصة كاري-كاتشب حارة ومرشوشة بمسحوق الكاري، تقدم مع بطاطس مقلية. أيقونة شارع برلين.",
  },
  {
    id: "french-jambon-beurre",
    name: "Jambon-Beurre Baguette", nameEs: "Baguette Jambon-Beurre", nameAr: "باغيت جامبون بور",
    category: "quick-lunch", regions: ["europe"], emoji: "🥖", calories: "380-440 kcal",
    desc: "The simplest Parisian lunch: a fresh baguette spread with good butter and filled with quality Parisian ham. Three ingredients, perfection.",
    descEs: "El almuerzo parisino más simple: una baguette fresca untada con buena mantequilla y rellena de jamón parisino de calidad. Tres ingredientes, perfección.",
    descAr: "أبسط غداء باريسي: باغيت طازج مدهون بزبدة جيدة ومحشو بلحم خنزير باريسي عالي الجودة. ثلاثة مكونات، كمال.",
  },

  // ===== EUROPE — Budget-Friendly Bites =====
  {
    id: "beans-on-toast",
    name: "Beans on Toast", nameEs: "Frijoles sobre Tostada", nameAr: "فاصوليا على التوست",
    category: "budget-meals", regions: ["europe"], emoji: "🫘", calories: "350-450 kcal",
    desc: "Heinz baked beans in tomato sauce piled on buttered toast with grated cheddar. The UK's most honest budget meal, ready in 3 minutes.",
    descEs: "Frijoles horneados Heinz en salsa de tomate sobre tostada con mantequilla y queso cheddar rallado. La comida económica más honesta del Reino Unido.",
    descAr: "فاصوليا هاينز المخبوزة في صلصة الطماطم على توست بالزبدة مع جبن شيدر مبشور. أشهر وجبة اقتصادية بريطانية، جاهزة في 3 دقائق.",
  },
  {
    id: "spaghetti-carbonara",
    name: "Spaghetti Carbonara", nameEs: "Espaguetis Carbonara", nameAr: "سباغيتي كاربونارا",
    category: "budget-meals", regions: ["europe"], emoji: "🍝", calories: "500-600 kcal",
    desc: "Authentic Roman carbonara: spaghetti tossed with crispy guanciale, egg yolks, Pecorino Romano, and black pepper. No cream — ever.",
    descEs: "Carbonara romana auténtica: espaguetis mezclados con guanciale crujiente, yemas de huevo, Pecorino Romano y pimienta negra. Sin crema — nunca.",
    descAr: "كاربونارا رومانية أصيلة: سباغيتي مخلوطة بغوانشيالي مقرمش وصفار البيض وجبن بيكورينو رومانو وفلفل أسود. بدون كريمة — أبداً.",
  },
  {
    id: "french-omelette",
    name: "French Herbed Omelette", nameEs: "Omelette Francés a las Finas Hierbas", nameAr: "أومليت فرنسي بالأعشاب",
    category: "budget-meals", regions: ["europe"], emoji: "🥚", calories: "280-350 kcal",
    desc: "Classic French rolled omelette — pale yellow, just-set, filled with fines herbes and Gruyère. Served with a simple green salad. Bistro quality at home.",
    descEs: "Clásico omelette francés enrollado: amarillo pálido, apenas cuajado, relleno de finas hierbas y Gruyère. Calidad de bistró en casa.",
    descAr: "أومليت فرنسي كلاسيكي ملفوف: أصفر باهت، طري، محشو بالأعشاب الفرنسية وجبن غرويير. جودة المطعم في المنزل.",
  },
  {
    id: "patatas-bravas",
    name: "Patatas Bravas", nameEs: "Patatas Bravas", nameAr: "باتاتاس برافاس",
    category: "budget-meals", regions: ["europe"], emoji: "🥔", calories: "320-400 kcal",
    desc: "Crispy fried potato cubes topped with spicy bravas sauce, garlic aioli, and chopped parsley. The ultimate Spanish tapas meets budget comfort.",
    descEs: "Cubos de papa frita crujientes cubiertos con salsa brava picante, alioli de ajo y perejil picado. El tapeo español definitivo.",
    descAr: "مكعبات بطاطس مقلية مقرمشة مغطاة بصلصة برافا الحارة وأيولي الثوم والبقدونس المفروم. طبق مقبلات إسباني رائع.",
  },
  {
    id: "pasta-puttanesca",
    name: "Spaghetti Puttanesca", nameEs: "Espaguetis a la Puttanesca", nameAr: "سباغيتي بوتانيسكا",
    category: "budget-meals", regions: ["europe"], emoji: "🍝", calories: "380-480 kcal",
    desc: "Southern Italian pantry pasta with tomatoes, olives, capers, garlic, anchovies, and chili flakes. Bold, briny, made entirely from cupboard staples.",
    descEs: "Pasta sureña italiana con tomates, aceitunas, alcaparras, ajo, anchoas y hojuelas de chile. Audaz, salada, hecha enteramente del armario.",
    descAr: "معكرونة إيطالية جنوبية بالطماطم والزيتون والكبر والثوم والأنشوجة ورقائق الفلفل الحار. جريئة ومالحة، مصنوعة بالكامل من المؤن.",
  },
  {
    id: "cheese-and-onion-pasty",
    name: "Cheese & Onion Pasty", nameEs: "Empanada de Queso y Cebolla", nameAr: "فطيرة الجبن والبصل",
    category: "budget-meals", regions: ["europe"], emoji: "🥟", calories: "400-500 kcal",
    desc: "Flaky golden pastry filled with melted cheddar, potato, onion, and a touch of English mustard. Grab-and-go British bakery classic.",
    descEs: "Hojaldre dorado relleno de queso cheddar derretido, papa, cebolla y un toque de mostaza inglesa. Clásico de panadería británica para llevar.",
    descAr: "عجينة ذهبية مقرمشة محشوة بجبن شيدر مذاب وبطاطس وبصل وقليل من الخردل الإنجليزي. وجبة مخبز بريطانية كلاسيكية.",
  },
  {
    id: "gnocchi-pomodoro",
    name: "Gnocchi al Pomodoro", nameEs: "Ñoquis al Pomodoro", nameAr: "نيوكي آل بومودورو",
    category: "budget-meals", regions: ["europe"], emoji: "🍝", calories: "380-460 kcal",
    desc: "Potato gnocchi in simple tomato-basil sauce with a shower of Parmigiano. Pillowy Italian comfort from a €2 pack of shelf-stable gnocchi.",
    descEs: "Ñoquis de papa en salsa simple de tomate y albahaca con Parmigiano. Confort italiano desde un paquete de ñoquis de €2.",
    descAr: "نيوكي البطاطس في صلصة طماطم وريحان بسيطة مع بارميجيانو. طعام إيطالي مريح من علبة نيوكي جاهزة.",
  },
  {
    id: "german-potato-soup",
    name: "German Potato Soup", nameEs: "Sopa de Papa Alemana", nameAr: "حساء البطاطس الألماني",
    category: "budget-meals", regions: ["europe"], emoji: "🍲", calories: "300-400 kcal",
    desc: "Creamy kartoffelsuppe with potatoes, carrots, leeks, and frankfurter slices. Topped with fresh parsley and crusty bread on the side. German grandma recipe.",
    descEs: "Kartoffelsuppe cremosa con papas, zanahorias, puerros y trozos de salchicha frankfurter. Receta de la abuela alemana.",
    descAr: "حساء بطاطس ألماني كريمي مع البطاطس والجزر والكراث وقطع نقانق فرانكفورتر. وصفة الجدة الألمانية.",
  },

  // ===== EUROPE — Low-Cal Healthy Picks =====
  {
    id: "nicoise-salad",
    name: "Salade Niçoise", nameEs: "Ensalada Niçoise", nameAr: "سلطة نيسواز",
    category: "fitness-diet", regions: ["europe"], emoji: "🥗", calories: "350-430 kcal",
    desc: "Classic French composed salad: seared tuna, hard-boiled eggs, green beans, olives, anchovies, tomatoes, and new potatoes with Dijon vinaigrette.",
    descEs: "Ensalada francesa clásica: atún sellado, huevos duros, judías verdes, aceitunas, anchoas, tomates y papas nuevas con vinagreta de Dijon.",
    descAr: "سلطة فرنسية كلاسيكية: تونة مشوية وبيض مسلوق وفاصوليا خضراء وزيتون وأنشوجة وطماطم وبطاطس جديدة مع خل ديجون.",
  },
  {
    id: "greek-horiatiki",
    name: "Greek Village Salad", nameEs: "Ensalada Griega de Pueblo", nameAr: "سلطة قروية يونانية",
    category: "fitness-diet", regions: ["europe"], emoji: "🥗", calories: "280-350 kcal",
    desc: "Horiatiki: ripe tomatoes, cucumber, green pepper, red onion, kalamata olives, and a thick slab of feta. Dressed with olive oil and oregano. No lettuce.",
    descEs: "Horiatiki: tomates maduros, pepino, pimiento verde, cebolla roja, aceitunas kalamata y una gruesa porción de feta. Sin lechuga.",
    descAr: "هورياتيكي: طماطم ناضجة وخيار وفلفل أخضر وبصل أحمر وزيتون كالاماتا وقطعة سميكة من جبن الفيتا. بدون خس.",
  },
  {
    id: "ratatouille",
    name: "Provençal Ratatouille", nameEs: "Ratatouille Provenzal", nameAr: "راتاتوي بروفنسالي",
    category: "fitness-diet", regions: ["europe"], emoji: "🍆", calories: "200-280 kcal",
    desc: "Slow-cooked Provençal vegetable stew: eggplant, zucchini, bell peppers, tomatoes, and herbs. A rainbow of Mediterranean vegetables in one bowl.",
    descEs: "Guiso provenzal de verduras cocinado lentamente: berenjena, calabacín, pimientos, tomates y hierbas. Un arcoíris mediterráneo en un plato.",
    descAr: "يخنة خضروات بروفنسالية مطهوة ببطء: باذنجان وكوسا وفلفل حلو وطماطم وأعشاب. قوس قزح من الخضروات المتوسطية.",
  },
  {
    id: "grilled-sardines",
    name: "Portuguese Grilled Sardines", nameEs: "Sardinas a la Parrilla Portuguesas", nameAr: "سردين برتغالي مشوي",
    category: "fitness-diet", regions: ["europe"], emoji: "🐟", calories: "250-320 kcal",
    desc: "Fresh sardines grilled over charcoal with sea salt, lemon, and olive oil. Served with a simple tomato salad. Lisbon summer on a plate.",
    descEs: "Sardinas frescas a la parrilla con sal marina, limón y aceite de oliva. Servidas con ensalada de tomate. Verano de Lisboa en un plato.",
    descAr: "سردين طازج مشوي على الفحم مع ملح البحر والليمون وزيت الزيتون. يقدم مع سلطة طماطم بسيطة. صيف لشبونة في طبق.",
  },
  {
    id: "minestrone",
    name: "Minestrone Soup", nameEs: "Sopa Minestrone", nameAr: "شوربة مينيستروني",
    category: "fitness-diet", regions: ["europe"], emoji: "🍲", calories: "220-300 kcal",
    desc: "Hearty Italian vegetable soup with cannellini beans, seasonal vegetables, tiny pasta, and a swirl of pesto. High fiber, deeply satisfying.",
    descEs: "Sopa italiana de verduras con frijoles cannellini, verduras de temporada, pasta pequeña y un toque de pesto. Alta en fibra, profundamente satisfactoria.",
    descAr: "حساء خضروات إيطالي شهي مع فاصوليا كانيليني وخضروات موسمية ومعكرونة صغيرة وقليل من البيستو. غني بالألياف ومرضٍ.",
  },
  {
    id: "caprese-salad",
    name: "Insalata Caprese", nameEs: "Ensalada Caprese", nameAr: "سلطة كابريزي",
    category: "fitness-diet", regions: ["europe"], emoji: "🍅", calories: "250-320 kcal",
    desc: "Thick slices of ripe tomato and fresh mozzarella di bufala, alternating on a plate with basil, extra virgin olive oil, and aged balsamic. Summer perfection.",
    descEs: "Gruesas rodajas de tomate maduro y mozzarella fresca de búfala, alternadas con albahaca, aceite de oliva virgen extra y balsámico añejo.",
    descAr: "شرائح سميكة من الطماطم الناضجة وجبن موزاريلا بوفالو الطازج، متناوبة على طبق مع الريحان وزيت الزيتون البكر الممتاز والخل البلسمي المعتق.",
  },
  {
    id: "mediterranean-grilled-fish",
    name: "Grilled Sea Bream", nameEs: "Dorada a la Parrilla", nameAr: "دنيس مشوي",
    category: "fitness-diet", regions: ["europe"], emoji: "🐟", calories: "280-350 kcal",
    desc: "Whole sea bream grilled with lemon, rosemary, and garlic. Served with grilled vegetables and a squeeze of fresh lemon. Mediterranean coastal staple.",
    descEs: "Dorada entera a la parrilla con limón, romero y ajo. Servida con verduras asadas y limón fresco. Básico de la costa mediterránea.",
    descAr: "سمك دنيس كامل مشوي بالليمون وإكليل الجبل والثوم. يقدم مع خضروات مشوية وعصرة ليمون طازج. طبق أساسي على الساحل المتوسطي.",
  },
  {
    id: "turkish-coban-salad",
    name: "Çoban Salatası", nameEs: "Ensalada Çoban", nameAr: "سلطة تشوبان",
    category: "fitness-diet", regions: ["europe", "middle-east"], emoji: "🥗", calories: "180-250 kcal",
    desc: "Turkish shepherd's salad: finely diced tomatoes, cucumber, onion, green pepper, and parsley with lemon-sumac dressing. Fresh, bright, and virtually zero fat.",
    descEs: "Ensalada de pastor turca: tomates, pepino, cebolla, pimiento verde y perejil picados finos con aderezo de limón y zumaque. Fresca y casi sin grasa.",
    descAr: "سلطة الراعي التركية: طماطم وخيار وبصل وفلفل أخضر وبقدونس مفرومة ناعماً مع صوص ليمون وسماق. طازجة وبلا دهون تقريباً.",
  },

  // ===== EUROPE — Comfort Food =====
  {
    id: "full-english-breakfast",
    name: "Full English Breakfast", nameEs: "Desayuno Inglés Completo", nameAr: "فطور إنجليزي كامل",
    category: "comfort-food", regions: ["europe"], emoji: "🍳", calories: "800-1000 kcal",
    desc: "Eggs, bacon, sausages, baked beans, grilled tomato, mushrooms, black pudding, and fried bread. The legendary British fry-up — breakfast for dinner.",
    descEs: "Huevos, tocino, salchichas, frijoles horneados, tomate a la parrilla, champiñones, morcilla y pan frito. El legendario desayuno británico.",
    descAr: "بيض ولحم مقدد ونقانق وفاصوليا مخبوزة وطماطم مشوية وفطر وبودينغ أسود وخبز مقلي. الفطور الإنجليزي الأسطوري.",
  },
  {
    id: "moussaka",
    name: "Greek Moussaka", nameEs: "Musaka Griega", nameAr: "مسقعة يونانية",
    category: "comfort-food", regions: ["europe", "middle-east"], emoji: "🍆", calories: "550-700 kcal",
    desc: "Layers of eggplant, seasoned ground lamb, and creamy béchamel baked until golden. Greece's answer to lasagna — rich, warming, and unforgettable.",
    descEs: "Capas de berenjena, cordero molido sazonado y bechamel cremosa horneadas hasta dorar. La respuesta griega a la lasaña.",
    descAr: "طبقات من الباذنجان ولحم الضأن المفروم المتبل والبشاميل الكريمي مخبوزة حتى تصبح ذهبية. رد اليونان على اللازانيا.",
  },
  {
    id: "wiener-schnitzel",
    name: "Wiener Schnitzel", nameEs: "Wiener Schnitzel", nameAr: "فينر شنيتزل",
    category: "comfort-food", regions: ["europe"], emoji: "🍖", calories: "600-750 kcal",
    desc: "Thin veal cutlet breaded and fried golden, served with lemon wedges, lingonberry jam, and warm potato salad. Austrian national treasure.",
    descEs: "Chuleta de ternera fina empanizada y frita dorada, servida con limón, mermelada de arándanos rojos y ensalada de papa. Tesoro nacional austriaco.",
    descAr: "شريحة لحم عجل رقيقة مغطاة بالبقسماط ومقلية حتى تصبح ذهبية، تقدم مع شرائح ليمون ومربى لينغونبيري وسلطة بطاطس دافئة. كنز نمساوي وطني.",
  },
  {
    id: "seafood-paella",
    name: "Seafood Paella", nameEs: "Paella de Mariscos", nameAr: "باييا المأكولات البحرية",
    category: "comfort-food", regions: ["europe"], emoji: "🥘", calories: "600-750 kcal",
    desc: "Saffron-scented bomba rice loaded with prawns, mussels, squid, and clams. Socarrat (crispy bottom) mandatory. Valencia's gift to the world.",
    descEs: "Arroz bomba perfumado con azafrán cargado de gambas, mejillones, calamares y almejas. Socarrat (fondo crujiente) obligatorio. El regalo de Valencia al mundo.",
    descAr: "أرز بومبا معطر بالزعفران محمل بالروبيان وبلح البحر والحبار والمحار. القاعدة المقرمشة إلزامية. هدية فالنسيا للعالم.",
  },
  {
    id: "fish-pie",
    name: "British Fish Pie", nameEs: "Pastel de Pescado Británico", nameAr: "فطيرة السمك البريطانية",
    category: "comfort-food", regions: ["europe"], emoji: "🐟", calories: "550-680 kcal",
    desc: "Smoked haddock, salmon, and prawns in creamy parsley sauce, topped with buttery mashed potato and baked golden. Ultimate British comfort in a dish.",
    descEs: "Abadejo ahumado, salmón y gambas en salsa cremosa de perejil, cubierto con puré de papa y horneado dorado. El máximo confort británico.",
    descAr: "حدوق مدخن وسلمون وروبيان في صلصة بقدونس كريمية، مغطاة بهريس البطاطس بالزبدة ومخبوزة حتى تصبح ذهبية. الراحة البريطانية القصوى.",
  },
  {
    id: "beef-bourguignon",
    name: "Beef Bourguignon", nameEs: "Bœuf Bourguignon", nameAr: "بيف بورغينيون",
    category: "comfort-food", regions: ["europe"], emoji: "🍲", calories: "550-700 kcal",
    desc: "Beef slowly braised in Burgundy wine with pearl onions, mushrooms, and lardons. Julia Child made this famous for a reason. Served with crusty bread.",
    descEs: "Carne de res estofada en vino de Borgoña con cebollas perla, champiñones y lardones. Julia Child hizo famoso esto por una razón.",
    descAr: "لحم بقري مطهو ببطء في نبيذ بورغندي مع بصل لؤلؤي وفطر ولحم مقدد. جوليا تشايلد جعلت هذا مشهوراً لسبب.",
  },
  {
    id: "bangers-and-mash",
    name: "Bangers & Mash", nameEs: "Salchichas con Puré", nameAr: "بانغرز آند ماش",
    category: "comfort-food", regions: ["europe"], emoji: "🌭", calories: "600-750 kcal",
    desc: "Plump British pork sausages on a mountain of buttery mashed potatoes, drowning in rich onion gravy. Pub food perfection. Add mushy peas to complete.",
    descEs: "Salchichas británicas de cerdo sobre puré de papa con mantequilla, bañadas en salsa de cebolla. Perfección de pub. Agrega guisantes.",
    descAr: "نقانق لحم خنزير بريطانية ممتلئة على جبل من هريس البطاطس بالزبدة، مغمورة بصلصة البصل الغنية. طعام حانة مثالي.",
  },
  {
    id: "belgian-moules-frites",
    name: "Moules-Frites", nameEs: "Mejillones con Papas Fritas", nameAr: "مول فريت",
    category: "comfort-food", regions: ["europe"], emoji: "🦪", calories: "550-700 kcal",
    desc: "Kilogram of mussels steamed in white wine, garlic, and cream, served with a towering cone of double-fried Belgian frites and garlic mayo. Brussels classic.",
    descEs: "Un kilo de mejillones al vapor en vino blanco, ajo y crema, servidos con un cono de papas fritas belgas. Clásico de Bruselas.",
    descAr: "كيلوغرام من بلح البحر مطهو على البخار في نبيذ أبيض وثوم وكريمة، يقدم مع مخروط من البطاطس المقلية البلجيكية. طبق بروكسل الكلاسيكي.",
  },

  // ===== MIDDLE EAST — Quick Office Lunch =====
  {
    id: "falafel-wrap",
    name: "Falafel Wrap", nameEs: "Wrap de Falafel", nameAr: "لفافة فلافل",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🧆", calories: "420-500 kcal",
    desc: "Crispy chickpea falafel balls in warm pita with pickled turnips, tomatoes, lettuce, and tahini sauce. The king of Middle Eastern street food.",
    descEs: "Bolitas crujientes de falafel de garbanzo en pita caliente con nabos encurtidos, tomates, lechuga y salsa tahini. El rey de la comida callejera.",
    descAr: "كرات فلافل حمص مقرمشة في خبز بيتا دافئ مع لفت مخلل وطماطم وخس وصلصة طحينة. ملك طعام الشارع في الشرق الأوسط.",
  },
  {
    id: "chicken-shawarma",
    name: "Chicken Shawarma Plate", nameEs: "Plato de Shawarma de Pollo", nameAr: "طبق شاورما دجاج",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🌯", calories: "480-580 kcal",
    desc: "Spit-roasted seasoned chicken shaved thin, served with hummus, garlic toum, pickles, and warm pita. The Levantine lunch that conquered the world.",
    descEs: "Pollo asado al espeto sazonado y cortado fino, servido con hummus, toum de ajo, pepinillos y pita caliente. El almuerzo levantino que conquistó el mundo.",
    descAr: "دجاج مشوي على السيخ ومقطع رقيقاً، يقدم مع حمص وتوم بالثوم ومخلل وخبز بيتا دافئ. الغداء الشامي الذي غزا العالم.",
  },
  {
    id: "manakish-zaatar",
    name: "Manakish Za'atar", nameEs: "Manakish Za'atar", nameAr: "مناقيش زعتر",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🫓", calories: "300-380 kcal",
    desc: "Freshly baked flatbread topped with za'atar spice blend, olive oil, and sesame seeds. Rolled up with labneh, tomatoes, and fresh mint. Lebanese breakfast for lunch.",
    descEs: "Pan plano recién horneado cubierto con mezcla de za'atar, aceite de oliva y sésamo. Enrollado con labneh, tomates y menta fresca.",
    descAr: "خبز مسطح طازج مغطى بخليط الزعتر وزيت الزيتون وبذور السمسم. ملفوف مع لبنة وطماطم ونعناع طازج. فطور لبناني للغداء.",
  },
  {
    id: "lahmacun",
    name: "Lahmacun (Turkish Pizza)", nameEs: "Lahmacun (Pizza Turca)", nameAr: "لحم بعجين (بيتزا تركية)",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🍕", calories: "350-430 kcal",
    desc: "Thin crispy flatbread spread with spiced minced lamb-tomato mixture, baked until edges curl. Squeeze lemon, add parsley, roll up. Turkish street icon.",
    descEs: "Pan plano fino y crujiente cubierto con mezcla de cordero y tomate especiada. Exprime limón, agrega perejil, enrolla. Icono callejero turco.",
    descAr: "خبز رقيق مقرمش مغطى بخليط لحم الضأن المفروم والطماطم المتبل. اعصر ليموناً وأضف بقدونساً ولفه. رمز الشارع التركي.",
  },
  {
    id: "sabich-sandwich",
    name: "Sabich Sandwich", nameEs: "Sándwich Sabich", nameAr: "ساندويتش صبيح",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🥙", calories: "450-530 kcal",
    desc: "Warm pita stuffed with fried eggplant, hard-boiled egg, Israeli salad, hummus, amba (mango pickle), and tahini. Tel Aviv's ultimate breakfast-anytime.",
    descEs: "Pita caliente rellena de berenjena frita, huevo duro, ensalada israelí, hummus, amba y tahini. El desayuno definitivo de Tel Aviv.",
    descAr: "خبز بيتا دافئ محشو بباذنجان مقلي وبيض مسلوق وسلطة إسرائيلية وحمص و عمبة (مخلل مانجو) وطحينة. فطور تل أبيب المثالي.",
  },
  {
    id: "balila-hummus-bowl",
    name: "Hummus & Balila Bowl", nameEs: "Bol de Hummus y Balila", nameAr: "طبق حمص وبليلة",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🫘", calories: "380-460 kcal",
    desc: "Silky hummus topped with warm whole chickpeas (balila), cumin, olive oil, and pine nuts. Served with pickles and fresh pita. Beirut lunch classic.",
    descEs: "Hummus sedoso cubierto con garbanzos enteros calientes (balila), comino, aceite de oliva y piñones. Servido con pepinillos y pita fresca.",
    descAr: "حمص ناعم مغطى بحمص حب دافئ (بليلة) وكمون وزيت زيتون وصنوبر. يقدم مع مخلل وخبز بيتا طازج. غداء بيروتي كلاسيكي.",
  },
  {
    id: "ayran-kebab-wrap",
    name: "Kebab Wrap with Ayran", nameEs: "Wrap de Kebab con Ayran", nameAr: "لفافة كباب مع عيران",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🥙", calories: "480-560 kcal",
    desc: "Char-grilled adana kebab in lavaş bread with sumac onions, tomato, parsley, and a side of cold ayran (savory yogurt drink). Complete Turkish lunch.",
    descEs: "Kebab adana a la parrilla en pan lavaş con cebollas al zumaque, tomate, perejil y ayran frío. Almuerzo turco completo.",
    descAr: "كباب أضنة مشوي على الفحم في خبز لافاش مع بصل السماق وطماطم وبقدونس وعيران بارد. غداء تركي كامل.",
  },
  {
    id: "fattoush-grilled-halloumi",
    name: "Fattoush with Halloumi", nameEs: "Fattoush con Halloumi", nameAr: "فتوش مع حلوم",
    category: "quick-lunch", regions: ["middle-east"], emoji: "🥗", calories: "380-460 kcal",
    desc: "Crisp fattoush salad with toasted pita chips, sumac, radish, cucumber, and grilled halloumi cheese. The crunchiest salad you'll ever eat.",
    descEs: "Ensalada fattoush crujiente con chips de pita tostada, zumaque, rábano, pepino y queso halloumi a la parrilla. La ensalada más crujiente.",
    descAr: "سلطة فتوش مقرمشة مع رقائق بيتا محمصة وسماق وفجل وخيار وجبن حلوم مشوي. أكثر سلطة مقرمشة ستأكلها.",
  },

  // ===== MIDDLE EAST — Budget-Friendly Bites =====
  {
    id: "mujadara",
    name: "Mujadara", nameEs: "Mujadara", nameAr: "مجدرة",
    category: "budget-meals", regions: ["middle-east"], emoji: "🍚", calories: "350-420 kcal",
    desc: "Lentils and rice cooked with cumin, topped with mounds of crispy caramelized onions and a dollop of yogurt. The ultimate Middle Eastern pantry meal.",
    descEs: "Lentejas y arroz cocinados con comino, cubiertos con cebollas caramelizadas crujientes y yogur. La comida de despensa definitiva del Medio Oriente.",
    descAr: "عدس وأرز مطهو مع كمون، مغطى ببصل مكرمل مقرمش ولبن زبادي. وجبة المؤونة المثالية في الشرق الأوسط.",
  },
  {
    id: "koshari",
    name: "Egyptian Koshari", nameEs: "Koshari Egipcio", nameAr: "كشري مصري",
    category: "budget-meals", regions: ["middle-east"], emoji: "🍲", calories: "420-520 kcal",
    desc: "Egypt's national street dish: layers of rice, macaroni, lentils, chickpeas, crispy onions, and tangy tomato-garlic sauce. Under $1 in Cairo, tastes like a million.",
    descEs: "El plato callejero nacional de Egipto: capas de arroz, macarrones, lentejas, garbanzos, cebollas crujientes y salsa de tomate y ajo.",
    descAr: "الطبق الوطني المصري: طبقات من الأرز والمعكرونة والعدس والحمص والبصل المقرمش وصلصة الطماطم والثوم. بأقل من دولار في القاهرة.",
  },
  {
    id: "ful-medames",
    name: "Ful Medames", nameEs: "Ful Medames", nameAr: "فول مدمس",
    category: "budget-meals", regions: ["middle-east"], emoji: "🫘", calories: "300-380 kcal",
    desc: "Slow-cooked fava beans seasoned with cumin, lemon, garlic, and olive oil. Served with warm pita, chopped tomatoes, and a boiled egg. Egyptian breakfast staple.",
    descEs: "Habas cocinadas lentamente sazonadas con comino, limón, ajo y aceite de oliva. Servidas con pita caliente, tomate picado y huevo duro.",
    descAr: "فول مطهو ببطء متبل بالكمون والليمون والثوم وزيت الزيتون. يقدم مع خبز بيتا دافئ وطماطم مفرومة وبيض مسلوق. فطور مصري أساسي.",
  },
  {
    id: "turkish-red-lentil-soup",
    name: "Mercimek Çorbası", nameEs: "Sopa de Lentejas Rojas Turca", nameAr: "شوربة عدس أحمر تركية",
    category: "budget-meals", regions: ["middle-east"], emoji: "🍲", calories: "250-330 kcal",
    desc: "Velvety Turkish red lentil soup with paprika butter drizzle and lemon squeeze. Served at every Turkish home and lokanta. Costs pennies, feels luxurious.",
    descEs: "Sopa aterciopelada de lentejas rojas turca con mantequilla de pimentón y limón. Servida en cada hogar y lokanta turca. Cuesta centavos, se siente lujosa.",
    descAr: "شوربة عدس أحمر تركية مخملية مع زبدة البابريكا وعصرة ليمون. تقدم في كل بيت ومطعم تركي. تكلف قليلاً وتشعر بالفخامة.",
  },
  {
    id: "falafel-hummus-plate",
    name: "Falafel & Hummus Plate", nameEs: "Plato de Falafel y Hummus", nameAr: "طبق فلافل وحمص",
    category: "budget-meals", regions: ["middle-east"], emoji: "🧆", calories: "450-550 kcal",
    desc: "6 crispy falafel balls alongside silky hummus, Israeli salad, pickles, and warm pita. The classic Middle Eastern platter — filling, fresh, and affordable.",
    descEs: "6 bolitas de falafel crujientes con hummus sedoso, ensalada israelí, pepinillos y pita caliente. El plato clásico del Medio Oriente.",
    descAr: "6 كرات فلافل مقرمشة مع حمص ناعم وسلطة إسرائيلية ومخلل وخبز بيتا دافئ. الطبق الشرق أوسطي الكلاسيكي — مشبع وطازج وبسعر معقول.",
  },
  {
    id: "batata-harra",
    name: "Batata Harra", nameEs: "Batata Harra", nameAr: "بطاطا حارة",
    category: "budget-meals", regions: ["middle-east"], emoji: "🥔", calories: "300-380 kcal",
    desc: "Crispy cubed potatoes sautéed with garlic, fresh cilantro, chili, and lemon. The Lebanese spicy potato that turns a side dish into the main event.",
    descEs: "Papas en cubos crujientes salteadas con ajo, cilantro fresco, chile y limón. La papa picante libanesa que convierte un acompañamiento en plato principal.",
    descAr: "بطاطس مكعبات مقرمشة مقلية مع ثوم وكزبرة طازجة وفلفل حار وليمون. البطاطس اللبنانية الحارة التي تحول الطبق الجانبي إلى نجم.",
  },
  {
    id: "shakshuka",
    name: "Shakshuka", nameEs: "Shakshuka", nameAr: "شكشوكة",
    category: "budget-meals", regions: ["middle-east"], emoji: "🍳", calories: "320-400 kcal",
    desc: "Eggs poached in spiced tomato-pepper sauce with cumin, paprika, and harissa. Scooped up with crusty bread. North African-Middle Eastern brunch champion.",
    descEs: "Huevos escalfados en salsa de tomate y pimiento especiada con comino, pimentón y harissa. Campeón del brunch norteafricano y del Medio Oriente.",
    descAr: "بيض مسلوق في صلصة طماطم وفلفل متبلة بالكمون والبابريكا والهريسة. يغرف بالخبز. بطل الفطور المتأخر في شمال أفريقيا والشرق الأوسط.",
  },
  {
    id: "turkish-pide",
    name: "Cheese Pide", nameEs: "Pide de Queso", nameAr: "بيدة بالجبن",
    category: "budget-meals", regions: ["middle-east"], emoji: "🚢", calories: "400-500 kcal",
    desc: "Turkish boat-shaped flatbread filled with melted kasar cheese, beyaz peynir (white cheese), and egg. Baked until golden. Better than pizza, cheaper than pizza.",
    descEs: "Pan plano turco en forma de barco relleno de queso kasar derretido y huevo. Mejor y más barato que la pizza.",
    descAr: "خبز تركي مسطح على شكل قارب محشو بجبن قشقوان مذاب وجبن أبيض وبيض. أفضل وأرخص من البيتزا.",
  },

  // ===== MIDDLE EAST — Low-Cal Healthy Picks =====
  {
    id: "tabbouleh",
    name: "Tabbouleh", nameEs: "Tabulé", nameAr: "تبولة",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🥬", calories: "180-250 kcal",
    desc: "Lebanese parsley salad with bulgur wheat, finely diced tomatoes, mint, green onion, lemon juice, and olive oil. More herb than grain — the Lebanese way.",
    descEs: "Ensalada libanesa de perejil con trigo bulgur, tomates picados, menta, cebollín, jugo de limón y aceite de oliva. Más hierba que grano.",
    descAr: "سلطة بقدونس لبنانية مع برغل وطماطم مفرومة ناعماً ونعناع وبصل أخضر وعصير ليمون وزيت زيتون. أعشاب أكثر من حبوب — الطريقة اللبنانية.",
  },
  {
    id: "grilled-kofta",
    name: "Grilled Kofta Skewers", nameEs: "Brochetas de Kofta a la Parrilla", nameAr: "أسياخ كفتة مشوية",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🍢", calories: "320-400 kcal",
    desc: "Lean ground lamb and beef mixed with parsley, onion, and spices, grilled on skewers. Served with grilled vegetables and a squeeze of lemon.",
    descEs: "Carne magra de cordero y res mezclada con perejil, cebolla y especias, a la parrilla en brochetas. Servida con verduras asadas y limón.",
    descAr: "لحم ضأن وبقر مفروم خالي الدهن مخلوط بالبقدونس والبصل والتوابل، مشوي على أسياخ. يقدم مع خضروات مشوية وعصرة ليمون.",
  },
  {
    id: "stuffed-grape-leaves",
    name: "Warak Enab (Stuffed Grape Leaves)", nameEs: "Hojas de Parra Rellenas", nameAr: "ورق عنب محشي",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🍃", calories: "250-320 kcal",
    desc: "Tender grape leaves wrapped around rice, herbs, and tomato. Cooked in lemon-olive oil. Served cold as part of a mezze spread. Light and refreshing.",
    descEs: "Hojas de parra tiernas envueltas alrededor de arroz, hierbas y tomate. Cocinadas en limón y aceite de oliva. Ligeras y refrescantes.",
    descAr: "ورق عنب طري ملفوف حول أرز وأعشاب وطماطم. مطهو في ليمون وزيت زيتون. خفيف ومنعش.",
  },
  {
    id: "grilled-chicken-tawook",
    name: "Chicken Tawook Salad", nameEs: "Ensalada de Pollo Tawook", nameAr: "سلطة دجاج طاووق",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🥗", calories: "350-430 kcal",
    desc: "Yogurt-lemon marinated grilled chicken breast over fattoush-style greens with pomegranate dressing. Lebanese gym-goer's favorite protein hit.",
    descEs: "Pechuga de pollo marinada en yogur y limón a la parrilla sobre verduras con aderezo de granada. Favorito del gimnasio libanés.",
    descAr: "صدر دجاج متبل بالزبادي والليمون ومشوي على خضروات مشكلة مع صوص الرمان. وجبة البروتين المفضلة لرواد الصالات الرياضية اللبنانيين.",
  },
  {
    id: "lentil-spinach-soup",
    name: "Lebanese Lentil & Spinach Soup", nameEs: "Sopa Libanesa de Lentejas y Espinacas", nameAr: "شوربة عدس وسبانخ لبنانية",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🍲", calories: "220-300 kcal",
    desc: "Red lentils and fresh spinach simmered with cumin, turmeric, and lemon. Silky, protein-packed, and ready in 20 minutes. Vegan Lebanese comfort.",
    descEs: "Lentejas rojas y espinacas frescas cocidas con comino, cúrcuma y limón. Sedosa, llena de proteínas y lista en 20 minutos. Confort vegano libanés.",
    descAr: "عدس أحمر وسبانخ طازجة مطهوة مع كمون وكركم وليمون. حريرية وغنية بالبروتين وجاهزة في 20 دقيقة. راحة نباتية لبنانية.",
  },
  {
    id: "irani-grilled-veg",
    name: "Persian Herb & Feta Plate", nameEs: "Plato Persa de Hierbas y Queso Feta", nameAr: "طبق أعشاب وجبن فيتا فارسي",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🧀", calories: "280-350 kcal",
    desc: "Sabzi khordan: a vibrant plate of fresh herbs (mint, basil, tarragon), radish, walnuts, and feta-style cheese with lavash bread. Iranian picnic on a plate.",
    descEs: "Sabzi khordan: un plato vibrante de hierbas frescas (menta, albahaca, estragón), rábano, nueces y queso tipo feta con pan lavash. Picnic iraní en un plato.",
    descAr: "سبزي خوردن: طبق نابض بالحياة من الأعشاب الطازجة (نعناع وريحان وطرخون) وفجل وجوز وجبن فيتا مع خبز لافاش. نزهة إيرانية في طبق.",
  },
  {
    id: "grilled-fish-sayadieh",
    name: "Sayadieh Fish", nameEs: "Pescado Sayadieh", nameAr: "سمك صيادية",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🐟", calories: "320-400 kcal",
    desc: "Pan-seared white fish seasoned with cumin and turmeric, served on fragrant rice with caramelized onions and tahini sauce. Lebanese coastal classic, light style.",
    descEs: "Pescado blanco a la plancha sazonado con comino y cúrcuma, sobre arroz fragante con cebollas caramelizadas y salsa tahini. Clásico costero libanés ligero.",
    descAr: "سمك أبيض مقلي في المقلاة متبل بالكمون والكركم، على أرز معطر مع بصل مكرمل وصلصة طحينة. طبق ساحلي لبناني كلاسيكي خفيف.",
  },
  {
    id: "cacik",
    name: "Cacık (Turkish Yogurt Soup)", nameEs: "Cacık (Sopa de Yogur Turca)", nameAr: "جاجيك (شوربة زبادي تركية)",
    category: "fitness-diet", regions: ["middle-east"], emoji: "🥒", calories: "150-220 kcal",
    desc: "Cold yogurt soup with finely diced cucumber, fresh dill, mint, and a hint of garlic. Turkey's answer to tzatziki, served as a light meal with bread.",
    descEs: "Sopa fría de yogur con pepino picado fino, eneldo fresco, menta y ajo. La respuesta turca al tzatziki. Comida ligera con pan.",
    descAr: "شوربة زبادي باردة مع خيار مفروم ناعم وشبت طازج ونعناع وقليل من الثوم. رد تركيا على التزاتزيكي. وجبة خفيفة مع خبز.",
  },

  // ===== MIDDLE EAST — Comfort Food =====
  {
    id: "chicken-mandi",
    name: "Chicken Mandi", nameEs: "Pollo Mandi", nameAr: "دجاج مندي",
    category: "comfort-food", regions: ["middle-east"], emoji: "🍗", calories: "650-800 kcal",
    desc: "Yemeni-style slow-roasted spiced chicken on a bed of fragrant basmati rice infused with saffron, cardamom, and smoked charcoal. Arabian Peninsula showstopper.",
    descEs: "Pollo asado lentamente al estilo yemení sobre arroz basmati perfumado con azafrán, cardamomo y carbón ahumado. Espectáculo de la Península Arábiga.",
    descAr: "دجاج متبل مشوي ببطء على الطريقة اليمنية على سرير من أرز بسمتي معطر بالزعفران والهيل والفحم المدخن. جوهرة شبه الجزيرة العربية.",
  },
  {
    id: "mansaf",
    name: "Lamb Mansaf", nameEs: "Mansaf de Cordero", nameAr: "منسف لحم",
    category: "comfort-food", regions: ["middle-east"], emoji: "🍖", calories: "700-900 kcal",
    desc: "Jordan's national dish: tender lamb in fermented yogurt sauce (jameed) over a mountain of rice and thin shrak bread. Topped with almonds and pine nuts.",
    descEs: "El plato nacional de Jordania: cordero tierno en salsa de yogur fermentado (jameed) sobre arroz y pan shrak. Cubierto con almendras y piñones.",
    descAr: "الطبق الوطني الأردني: لحم ضأن طري في صلصة الجميد (لبن متخمر) فوق جبل من الأرز وخبز الشراك. مزين باللوز والصنوبر.",
  },
  {
    id: "iskender-kebab",
    name: "İskender Kebab", nameEs: "Kebab İskender", nameAr: "إسكندر كباب",
    category: "comfort-food", regions: ["middle-east"], emoji: "🍖", calories: "650-800 kcal",
    desc: "Thinly sliced döner over diced pide bread, smothered in hot tomato-butter sauce, served with grilled peppers and a dollop of yogurt. Bursa's greatest gift.",
    descEs: "Döner en láminas finas sobre pan pide, bañado en salsa caliente de tomate y mantequilla, con pimientos asados y yogur. El mejor regalo de Bursa.",
    descAr: "شرائح دونر رقيقة على خبز بيدة مقطع، مغمورة بصلصة طماطم وزبدة ساخنة، مع فلفل مشوي ولبن زبادي. أعظم هدية من بورصة.",
  },
  {
    id: "chicken-machboos",
    name: "Chicken Machboos", nameEs: "Pollo Machboos", nameAr: "مجبوس دجاج",
    category: "comfort-food", regions: ["middle-east"], emoji: "🍛", calories: "600-750 kcal",
    desc: "Bahraini spiced rice with tender chicken, dried limes (loomi), rose water, and saffron. Gulf-region biryani cousin — deeply aromatic and celebratory.",
    descEs: "Arroz especiado bareiní con pollo tierno, limas secas (loomi), agua de rosas y azafrán. Primo del biryani del Golfo: profundamente aromático.",
    descAr: "أرز بحريني متبل مع دجاج طري ولومي (ليمون مجفف) وماء ورد وزعفران. قريب البرياني الخليجي — عطري واحتفالي.",
  },
  {
    id: "ghormeh-sabzi",
    name: "Ghormeh Sabzi", nameEs: "Ghormeh Sabzi", nameAr: "قورمه سبزي",
    category: "comfort-food", regions: ["middle-east"], emoji: "🍲", calories: "500-650 kcal",
    desc: "Persian herb stew with lamb, kidney beans, dried limes, and a mountain of sautéed herbs. Simmered for hours. Iran's most beloved dish. Served with tahdig.",
    descEs: "Guiso persa de hierbas con cordero, frijoles rojos, limas secas y hierbas salteadas. El plato más querido de Irán. Servido con tahdig.",
    descAr: "يخنة أعشاب فارسية مع لحم ضأن وفاصوليا حمراء وليمون مجفف وجبل من الأعشاب المقلية. أكثر طبق محبوب في إيران. يقدم مع تهديغ.",
  },
  {
    id: "kibbeh-labanieh",
    name: "Kibbeh in Yogurt", nameEs: "Kibbeh en Yogur", nameAr: "كبة لبنية",
    category: "comfort-food", regions: ["middle-east"], emoji: "🧆", calories: "500-620 kcal",
    desc: "Stuffed bulgur-meat shells poached in warm mint-garlic yogurt sauce. Syrian-Lebanese holiday classic that turns simple ingredients into pure luxury.",
    descEs: "Croquetas de bulgur rellenas de carne escalfadas en salsa tibia de yogur, menta y ajo. Clásico festivo sirio-libanés.",
    descAr: "أقراص برغل محشية باللحم مسلوقة في صلصة زبادي دافئة بالنعناع والثوم. طبق أعياد سوري لبناني كلاسيكي.",
  },
  {
    id: "kunafa-nabulsi",
    name: "Kunafa Nabulsi", nameEs: "Kunafa Nabulsi", nameAr: "كنافة نابلسية",
    category: "comfort-food", regions: ["middle-east"], emoji: "🧀", calories: "550-700 kcal",
    desc: "Shredded phyllo dough sandwiching molten sweet cheese, soaked in rose-scented syrup, topped with crushed pistachios. Palestinian dessert that doubles as dinner.",
    descEs: "Phyllo rallado relleno de queso dulce fundido, empapado en jarabe de rosas, cubierto con pistachos. Postre palestino que también es cena.",
    descAr: "عجينة كنافة مبشورة تحتضن جبناً حلواً ذائباً، منقوعة في قطر معطر بماء الورد، مغطاة بفستق مطحون. حلوى فلسطينية تصلح عشاءً.",
  },
  {
    id: "mixed-grill-mashawi",
    name: "Mixed Mashawi Grill", nameEs: "Parrillada Mixta Mashawi", nameAr: "مشاوي مشكلة",
    category: "comfort-food", regions: ["middle-east"], emoji: "🥩", calories: "650-850 kcal",
    desc: "Generous platter of shish tawook, lamb kofta, and shish kebab over a bed of vermicelli rice with grilled vegetables, hummus, and garlic toum.",
    descEs: "Bandeja generosa de shish tawook, kofta de cordero y shish kebab sobre arroz con verduras asadas, hummus y toum de ajo.",
    descAr: "طبق سخي من شيش طاووق وكفتة غنم وشيش كباب على سرير من الأرز بالشعيرية مع خضروات مشوية وحمص وتوم بالثوم.",
  },

  // ===== LATIN AMERICA — Quick Office Lunch =====
  {
    id: "chicken-quesadilla-suiza",
    name: "Chicken Quesadilla Suiza", nameEs: "Quesadilla de Pollo Suiza", nameAr: "كويساديا دجاج سويسا",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🫔", calories: "480-560 kcal",
    desc: "Flour tortilla griddled golden with shredded chicken, Oaxaca cheese, and a smear of refried beans. Served with guacamole, crema, and salsa verde. Mexico City lunch.",
    descEs: "Tortilla de harina dorada con pollo desmenuzado, queso Oaxaca y frijoles refritos. Servida con guacamole, crema y salsa verde. Almuerzo de la CDMX.",
    descAr: "تورتيا طحين محمصة حتى تصبح ذهبية مع دجاج مقطع وجبن أواكساكا وطبقة من الفاصوليا المقلية. غداء مكسيكو سيتي.",
  },
  {
    id: "arepa-reina-pepiada",
    name: "Arepa Reina Pepiada", nameEs: "Arepa Reina Pepiada", nameAr: "أريبا رينا بيبيادا",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🫓", calories: "420-500 kcal",
    desc: "Venezuelan grilled corn cake split and stuffed with creamy chicken-avocado salad, cilantro, and a touch of lime. Named after a beauty queen, tastes like one too.",
    descEs: "Torta de maíz venezolana a la parrilla rellena de ensalada cremosa de pollo y aguacate, cilantro y limón. Nombrada en honor a una reina de belleza.",
    descAr: "كعكة ذرة فنزويلية مشوية محشوة بسلطة الدجاج والأفوكادو الكريمية والكزبرة والليمون. سميت تيمناً بملكة جمال وطعمها ملكي.",
  },
  {
    id: "tacos-al-pastor",
    name: "Tacos al Pastor", nameEs: "Tacos al Pastor", nameAr: "تاكوس الباستور",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🌮", calories: "380-480 kcal",
    desc: "Corn tortillas piled with spit-roasted marinated pork, fresh pineapple, diced onion, and cilantro. A squeeze of lime and salsa verde. Mexico's crown jewel.",
    descEs: "Tortillas de maíz con cerdo marinado asado al espeto, piña fresca, cebolla picada y cilantro. La joya de la corona de México.",
    descAr: "تورتيا ذرة محملة بلحم خنزير متبل مشوي على السيخ وأناناس طازج وبصل مفروم وكزبرة. جوهرة تاج المكسيك.",
  },
  {
    id: "ceviche-peruano",
    name: "Peruvian Ceviche", nameEs: "Ceviche Peruano", nameAr: "سيفيتشي بيروفي",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🐟", calories: "250-350 kcal",
    desc: "Fresh white fish 'cooked' in leche de tigre (lime juice, chili, ginger), with red onion, sweet potato, and giant-kernel corn. Lima's freshest lunch.",
    descEs: "Pescado blanco fresco 'cocinado' en leche de tigre (limón, ají, jengibre), con cebolla roja, batata y choclo. El almuerzo más fresco de Lima.",
    descAr: "سمك أبيض طازج 'مطهو' في حليب النمر (عصير ليمون وفلفل حار وزنجبيل)، مع بصل أحمر وبطاطا حلوة وذرة كبيرة. غداء ليما المنعش.",
  },
  {
    id: "cuban-sandwich",
    name: "Cuban Sandwich", nameEs: "Sándwich Cubano", nameAr: "ساندويتش كوبي",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🥪", calories: "520-620 kcal",
    desc: "Pressed Cuban bread layered with roast pork, ham, Swiss cheese, pickles, and mustard. Hot-pressed until crispy. Miami-meets-Havana lunch icon.",
    descEs: "Pan cubano prensado con cerdo asado, jamón, queso suizo, pepinillos y mostaza. Prensado caliente hasta crujir. Icono de almuerzo Miami-Habana.",
    descAr: "خبز كوبي مضغوط مع لحم خنزير مشوي ولحم خنزير مدخن وجبن سويسري ومخلل وخردل. أيقونة غداء ميامي-هافانا.",
  },
  {
    id: "saltenas",
    name: "Salteñas", nameEs: "Salteñas", nameAr: "سالتييناس",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🥟", calories: "380-460 kcal",
    desc: "Bolivian baked empanadas with a soupy-spiced beef and potato filling, olives, peas, and a hard-boiled egg piece. Slightly sweet golden dough. La Paz morning staple.",
    descEs: "Empanadas bolivianas horneadas con relleno jugoso de carne y papa, aceitunas, guisantes y huevo duro. Masa ligeramente dulce. Básico matutino de La Paz.",
    descAr: "فطائر بوليفية مخبوزة بحشوة لحم بقري وبطاطس حارة وزيتون وبازلاء وقطعة بيض مسلوق. عجين ذهبي حلو قليلاً. فطور لاباز.",
  },
  {
    id: "brazilian-coxinha",
    name: "Coxinha with Salad", nameEs: "Coxinha con Ensalada", nameAr: "كوكسينيا مع سلطة",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🍗", calories: "400-500 kcal",
    desc: "Teardrop-shaped dough filled with shredded chicken and cream cheese, breaded, and fried golden. Served with a side salad. Brazil's favorite snack turns lunch.",
    descEs: "Masa en forma de lágrima rellena de pollo desmenuzado y queso crema, empanizada y frita. Servida con ensalada. El snack favorito de Brasil se vuelve almuerzo.",
    descAr: "عجينة على شكل قطرة ماء محشوة بدجاج مقطع وجبن كريمي ومغطاة بالبقسماط ومقلية حتى تصبح ذهبية. الوجبة الخفيفة المفضلة في البرازيل تتحول إلى غداء.",
  },
  {
    id: "torta-ahogada",
    name: "Torta Ahogada", nameEs: "Torta Ahogada", nameAr: "تورتا أهوغادا",
    category: "quick-lunch", regions: ["latin-america"], emoji: "🥪", calories: "500-620 kcal",
    desc: "Crusty birote roll stuffed with carnitas, completely drowned in spicy chili de árbol sauce. Served with lime and radish. Guadalajara's messy, glorious lunch.",
    descEs: "Pan birote crujiente relleno de carnitas, completamente ahogado en salsa picante de chile de árbol. Almuerzo gloriosamente desordenado de Guadalajara.",
    descAr: "خبز بيروتي مقرمش محشو بلحم الكارنيتاس، مغمور بالكامل في صلصة الفلفل الحار. غداء غوادالاخارا الفوضوي والمجيد.",
  },

  // ===== LATIN AMERICA — Budget-Friendly Bites =====
  {
    id: "rice-and-beans",
    name: "Arroz con Frijoles", nameEs: "Arroz con Frijoles", nameAr: "أرز وفاصوليا",
    category: "budget-meals", regions: ["latin-america"], emoji: "🍚", calories: "380-480 kcal",
    desc: "The foundation of Latin American cuisine: perfectly seasoned rice alongside slow-cooked black or pinto beans. Add fried plantains and crema. Filling and under $2.",
    descEs: "La base de la cocina latinoamericana: arroz perfectamente sazonado con frijoles negros o pintos. Agrega plátano frito y crema. Llena y cuesta menos de $2.",
    descAr: "أساس المطبخ اللاتيني: أرز متبل بإتقان مع فاصوليا سوداء أو بينتو مطهوة ببطء. أضف موز مقلي وكريمة. مشبعة وبأقل من دولارين.",
  },
  {
    id: "pupusas",
    name: "Pupusas", nameEs: "Pupusas", nameAr: "بوبوساس",
    category: "budget-meals", regions: ["latin-america"], emoji: "🫓", calories: "350-450 kcal",
    desc: "Thick Salvadoran corn cakes stuffed with cheese, refried beans, and chicharrón. Griddled until crispy outside, gooey inside. Served with curtido and salsa roja.",
    descEs: "Tortillas gruesas salvadoreñas de maíz rellenas de queso, frijoles refritos y chicharrón. Servidas con curtido y salsa roja.",
    descAr: "كعكات ذرة سلفادورية سميكة محشوة بالجبن والفاصوليا المقلية وتشيتشارون. مشوية حتى تصبح مقرمشة من الخارج وطرية من الداخل.",
  },
  {
    id: "empanadas-argentinas",
    name: "Beef Empanadas", nameEs: "Empanadas de Carne", nameAr: "إمباناداس لحم",
    category: "budget-meals", regions: ["latin-america"], emoji: "🥟", calories: "350-450 kcal",
    desc: "Flaky baked pastry pockets filled with seasoned ground beef, olives, hard-boiled egg, and cumin. The Argentine grab-and-go icon. 3 empanadas = a meal.",
    descEs: "Bolsillos de hojaldre horneados rellenos de carne molida sazonada, aceitunas, huevo duro y comino. El icono argentino para llevar. 3 empanadas = una comida.",
    descAr: "جيوب عجين مقرمشة محشوة بلحم بقري مفروم متبل وزيتون وبيض مسلوق وكمون. أيقونة أرجنتينية للأكل السريع.",
  },
  {
    id: "chilaquiles",
    name: "Chilaquiles Rojos", nameEs: "Chilaquiles Rojos", nameAr: "تشيلاكيليس روجوس",
    category: "budget-meals", regions: ["latin-america"], emoji: "🍳", calories: "400-520 kcal",
    desc: "Day-old tortilla chips simmered in red salsa, topped with crema, queso fresco, sliced onion, and a fried egg. Mexico's best use of leftovers — breakfast for dinner.",
    descEs: "Totopos remojados en salsa roja, cubiertos con crema, queso fresco, cebolla en rodajas y huevo frito. El mejor uso mexicano de las sobras.",
    descAr: "رقائق تورتيا متبلة مغموسة في صلصة حمراء، مغطاة بالكريمة وجبن طازج وبصل مقطع وبيض مقلي. أفضل استخدام مكسيكي لبقايا الطعام.",
  },
  {
    id: "sopa-de-frijol",
    name: "Sopa de Frijol", nameEs: "Sopa de Frijol", nameAr: "حساء الفاصوليا",
    category: "budget-meals", regions: ["latin-america"], emoji: "🍲", calories: "280-380 kcal",
    desc: "Hearty Mexican bean soup made from scratch with pinto beans, epazote, onion, and chipotle. Topped with crispy tortilla strips and queso fresco. Soul-warming.",
    descEs: "Sopa de frijoles mexicana hecha con frijoles pintos, epazote, cebolla y chipotle. Cubierta con tiras de tortilla crujientes y queso fresco. Reconfortante.",
    descAr: "حساء فاصوليا مكسيكي شهي مصنوع من الفاصوليا والإيبازوتي والبصل وتشيبوتلي. مغطى بشرائح تورتيا مقرمشة وجبن طازج.",
  },
  {
    id: "pastel-de-papa",
    name: "Pastel de Papa", nameEs: "Pastel de Papa", nameAr: "باستيل دي بابا",
    category: "budget-meals", regions: ["latin-america"], emoji: "🥔", calories: "420-520 kcal",
    desc: "Argentine shepherd's pie: seasoned ground beef and olives under a thick layer of buttery mashed potato, baked golden. Buenos Aires abuela comfort on a budget.",
    descEs: "Pastel de carne argentino: carne molida sazonada y aceitunas bajo una capa de puré de papa con mantequilla, horneado dorado. El confort de la abuela de Buenos Aires.",
    descAr: "فطيرة راعي أرجنتينية: لحم بقري مفروم متبل وزيتون تحت طبقة سميكة من هريس البطاطس بالزبدة. راحة جدة بوينس آيرس.",
  },
  {
    id: "brazilian-pao-de-queijo",
    name: "Pão de Queijo", nameEs: "Pão de Queijo", nameAr: "باو دي كيجو",
    category: "budget-meals", regions: ["latin-america"], emoji: "🧀", calories: "300-400 kcal",
    desc: "Brazilian cheese bread: chewy, airy, gluten-free tapioca-flour puffs loaded with Minas cheese. Served warm from the oven. Addictive and surprisingly filling.",
    descEs: "Pan de queso brasileño: bolitas masticables de harina de tapioca sin gluten cargadas de queso Minas. Adictivas y sorprendentemente llenadoras.",
    descAr: "خبز جبن برازيلي: كرات مطاطية وهشة من دقيق التابيوكا خالية من الغلوتين محملة بجبن ميناس. تقدم دافئة من الفرن. مدمنة ومشبعة.",
  },
  {
    id: "colombian-arepa-egg",
    name: "Arepa de Huevo", nameEs: "Arepa de Huevo", nameAr: "أريبا دي ويفو",
    category: "budget-meals", regions: ["latin-america"], emoji: "🍳", calories: "350-430 kcal",
    desc: "Colombian corn cake deep-fried until puffed, cracked open and filled with a whole egg, then fried again. Golden, crispy, and oozing. Caribbean coast breakfast.",
    descEs: "Arepa colombiana frita hasta inflarse, abierta y rellena con un huevo entero, luego frita de nuevo. Dorada, crujiente y rebosante. Desayuno de la costa caribeña.",
    descAr: "كعكة ذرة كولومبية مقلية حتى تنتفخ، تفتح وتحشى ببيضة كاملة، ثم تقلى مرة أخرى. ذهبية ومقرمشة وتفيض. فطور الساحل الكاريبي.",
  },

  // ===== LATIN AMERICA — Low-Cal Healthy Picks =====
  {
    id: "peruvian-ceviche-classic",
    name: "Ceviche Clásico", nameEs: "Ceviche Clásico", nameAr: "سيفيتشي كلاسيكو",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🐟", calories: "220-300 kcal",
    desc: "Sea bass cured in fresh lime juice with red onion, cilantro, and aji limo chili. Served with sweet potato and choclo. Peru's national dish — pure lean protein.",
    descEs: "Lubina curada en jugo de limón fresco con cebolla roja, cilantro y ají limo. Servida con batata y choclo. El plato nacional del Perú: proteína pura y magra.",
    descAr: "سمك باس البحر معالج في عصير ليمون طازج مع بصل أحمر وكزبرة وفلفل أجي ليمو. يقدم مع بطاطا حلوة وتشوكلو. الطبق الوطني البيروفي.",
  },
  {
    id: "acai-bowl",
    name: "Açaí Bowl", nameEs: "Bol de Açaí", nameAr: "طبق أكاي",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🍇", calories: "300-380 kcal",
    desc: "Frozen açaí berry purée blended with banana, topped with granola, sliced fruit, and a drizzle of honey. Rio de Janeiro's gift to the fitness world.",
    descEs: "Puré de açaí congelado mezclado con plátano, cubierto con granola, fruta y miel. El regalo de Río de Janeiro al mundo fitness.",
    descAr: "هريس أكاي مجمد ممزوج بالموز، مغطى بالغرانولا والفاكهة المقطعة والعسل. هدية ريو دي جانيرو لعالم اللياقة.",
  },
  {
    id: "fish-tacos-baja",
    name: "Baja Fish Tacos", nameEs: "Tacos de Pescado Estilo Baja", nameAr: "تاكوس سمك باخا",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🌮", calories: "320-400 kcal",
    desc: "Grilled (not fried!) white fish in corn tortillas with shredded cabbage, pico de gallo, and cilantro-lime crema. Baja California surf culture on a plate.",
    descEs: "Pescado blanco a la parrilla (¡no frito!) en tortillas de maíz con col rallada, pico de gallo y crema de cilantro y lima. Cultura surf de Baja California.",
    descAr: "سمك أبيض مشوي (وليس مقلياً!) في تورتيا ذرة مع ملفوف مبشور وبيكو دي غايو وكريمة كزبرة ولايم. ثقافة ركوب الأمواج في باخا كاليفورنيا.",
  },
  {
    id: "nopales-salad",
    name: "Nopales Salad", nameEs: "Ensalada de Nopales", nameAr: "سلطة نوباليس",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🌵", calories: "150-220 kcal",
    desc: "Tender cactus paddles diced and tossed with tomato, onion, cilantro, queso fresco, and lime. High-fiber, low-cal Mexican superfood salad.",
    descEs: "Nopales tiernos cortados y mezclados con tomate, cebolla, cilantro, queso fresco y limón. Ensalada mexicana rica en fibra y baja en calorías.",
    descAr: "أوراق صبار طرية مقطعة ومخلوطة مع طماطم وبصل وكزبرة وجبن طازج وليمون. سلطة مكسيكية غنية بالألياف ومنخفضة السعرات.",
  },
  {
    id: "brazilian-grilled-fish",
    name: "Moqueca de Peixe (Light)", nameEs: "Moqueca de Pescado Ligera", nameAr: "موكيكا سمك خفيفة",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🐟", calories: "320-400 kcal",
    desc: "Bahian fish stew with tomatoes, bell peppers, coconut milk, and dendê oil. This light version uses less oil, more vegetables. Brazilian soul food made lean.",
    descEs: "Guiso de pescado bahiano con tomates, pimientos, leche de coco y aceite de dendê. Esta versión ligera usa menos aceite y más verduras.",
    descAr: "يخنة سمك باهيانية مع طماطم وفلفل حلو وحليب جوز الهند وزيت ديندي. هذه النسخة الخفيفة تستخدم زيتاً أقل وخضروات أكثر.",
  },
  {
    id: "quinoa-chaufa",
    name: "Quinoa Chaufa", nameEs: "Quinoa Chaufa", nameAr: "كينوا تشاوفا",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🍚", calories: "350-430 kcal",
    desc: "Peruvian-Chinese fried 'rice' made with quinoa instead of rice, with chicken, egg, scallions, and a touch of soy. All the flavor of chaufa, high-protein grain.",
    descEs: "Arroz frito peruano-chino hecho con quinoa en lugar de arroz, con pollo, huevo, cebollines y soja. Todo el sabor del chaufa con grano alto en proteínas.",
    descAr: "أرز مقلي بيروفي-صيني مصنوع من الكينوا بدلاً من الأرز، مع دجاج وبيض وبصل أخضر وقليل من صلصة الصويا. كل نكهة التشاوفا بحبوب عالية البروتين.",
  },
  {
    id: "ensalada-palmito",
    name: "Hearts of Palm Salad", nameEs: "Ensalada de Palmitos", nameAr: "سلطة قلب النخيل",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🥗", calories: "180-250 kcal",
    desc: "Sliced hearts of palm, avocado, cherry tomatoes, and arugula with lime vinaigrette. Light, elegant, and distinctly Brazilian. Popular at Rio beach kiosks.",
    descEs: "Palmitos en rodajas, aguacate, tomates cherry y rúcula con vinagreta de lima. Ligera, elegante y distintivamente brasileña. Popular en los kioscos de playa de Río.",
    descAr: "شرائح قلب النخيل وأفوكادو وطماطم كرزية وجرجير مع خل الليمون. خفيفة وأنيقة وبرازيلية بشكل مميز.",
  },
  {
    id: "argentine-grilled-provoleta",
    name: "Provoleta & Grilled Vegetables", nameEs: "Provoleta y Verduras Asadas", nameAr: "بروفوليتا وخضروات مشوية",
    category: "fitness-diet", regions: ["latin-america"], emoji: "🧀", calories: "350-430 kcal",
    desc: "Thick slice of provoleta cheese grilled until molten-crispy, served with a mountain of charred bell peppers, zucchini, and eggplant. Argentine asado goes green.",
    descEs: "Gruesa rebanada de queso provoleta a la parrilla hasta dorar, servida con pimientos, calabacín y berenjena asados. El asado argentino se vuelve verde.",
    descAr: "شريحة سميكة من جبن بروفوليتا مشوية حتى تذوب وتصبح مقرمشة، تقدم مع الفلفل الحلو والكوسا والباذنجان المشوي. أسادو أرجنتيني أخضر.",
  },

  // ===== LATIN AMERICA — Comfort Food =====
  {
    id: "feijoada",
    name: "Feijoada", nameEs: "Feijoada", nameAr: "فيجوادا",
    category: "comfort-food", regions: ["latin-america"], emoji: "🍲", calories: "700-900 kcal",
    desc: "Brazil's national dish: black bean stew with multiple cuts of pork and beef, slow-cooked for hours. Served with rice, collard greens, farofa, and orange slices.",
    descEs: "El plato nacional de Brasil: guiso de frijoles negros con múltiples cortes de cerdo y res. Servido con arroz, col rizada, farofa y naranja.",
    descAr: "الطبق الوطني البرازيلي: يخنة فاصوليا سوداء مع قطع متعددة من لحم الخنزير والبقر، مطهوة ببطء لساعات. تقدم مع أرز وكرنب أخضر وفاروفا وشرائح برتقال.",
  },
  {
    id: "lomo-saltado",
    name: "Lomo Saltado", nameEs: "Lomo Saltado", nameAr: "لومو سالتادو",
    category: "comfort-food", regions: ["latin-america"], emoji: "🥩", calories: "600-750 kcal",
    desc: "Stir-fried beef tenderloin with red onions, tomatoes, and aji amarillo, served with both French fries AND rice. Chinese-Peruvian fusion at its finest.",
    descEs: "Lomo de res salteado con cebolla roja, tomates y ají amarillo, servido con papas fritas Y arroz. Fusión chino-peruana en su máxima expresión.",
    descAr: "لحم بقري مقلي مع بصل أحمر وطماطم وأجي أماريلو، يقدم مع بطاطس مقلية وأرز. اندماج صيني-بيروفي في أبهى صورة.",
  },
  {
    id: "asado-argentino",
    name: "Argentine Asado", nameEs: "Asado Argentino", nameAr: "أسادو أرجنتيني",
    category: "comfort-food", regions: ["latin-america"], emoji: "🥩", calories: "750-950 kcal",
    desc: "Mixed grill of beef cuts (chorizo, morcilla, vacio, entraña) slow-cooked over wood coals, served with chimichurri. Argentina's Sunday ritual since forever.",
    descEs: "Parrillada mixta de cortes de res (chorizo, morcilla, vacío, entraña) cocinados sobre brasas, con chimichurri. El ritual dominical argentino.",
    descAr: "مشويات مشكلة من قطع اللحم البقري (تشوريزو ومورسيا وفاسيو وإنتranيا) مطهوة ببطء على فحم الخشب، تقدم مع تشيميتشوري. طقوس الأحد الأرجنتينية.",
  },
  {
    id: "mole-poblano",
    name: "Mole Poblano", nameEs: "Mole Poblano", nameAr: "مولي بوبلانو",
    category: "comfort-food", regions: ["latin-america"], emoji: "🍗", calories: "580-720 kcal",
    desc: "Chicken in a velvety dark sauce made from dried chiles, chocolate, nuts, spices, and seeds — 20+ ingredients. Puebla's legendary celebration dish.",
    descEs: "Pollo en salsa oscura aterciopelada hecha de chiles secos, chocolate, nueces, especias y semillas — 20+ ingredientes. El legendario plato festivo de Puebla.",
    descAr: "دجاج في صلصة داكنة مخملية مصنوعة من الفلفل المجفف والشوكولاتة والمكسرات والتوابل والبذور — أكثر من 20 مكوناً. طبق بويبلا الأسطوري للاحتفالات.",
  },
  {
    id: "bandeja-paisa",
    name: "Bandeja Paisa", nameEs: "Bandeja Paisa", nameAr: "باندخا بايسا",
    category: "comfort-food", regions: ["latin-america"], emoji: "🍳", calories: "800-1100 kcal",
    desc: "Colombia's mighty platter: grilled steak, chicharrón, chorizo, fried egg, rice, beans, avocado, sweet plantain, and arepa. Eat this and you won't need dinner.",
    descEs: "El poderoso plato colombiano: bistec, chicharrón, chorizo, huevo frito, arroz, frijoles, aguacate, plátano maduro y arepa. Come esto y no necesitarás cenar.",
    descAr: "طبق كولومبي مهيب: ستيك مشوي وتشيتشارون وتشوريزو وبيض مقلي وأرز وفاصوليا وأفوكادو وموز ناضج وأريبا. كل هذا ولن تحتاج للعشاء.",
  },
  {
    id: "pabellon-criollo",
    name: "Pabellón Criollo", nameEs: "Pabellón Criollo", nameAr: "بابيون كريولو",
    category: "comfort-food", regions: ["latin-america"], emoji: "🍛", calories: "550-700 kcal",
    desc: "Venezuela's national plate: shredded beef, black beans, white rice, and sweet fried plantains. Four components, each perfectly seasoned. The taste of Caracas.",
    descEs: "El plato nacional de Venezuela: carne mechada, frijoles negros, arroz blanco y plátano frito dulce. Cuatro componentes perfectamente sazonados. El sabor de Caracas.",
    descAr: "الطبق الوطني الفنزويلي: لحم بقري مقطع وفاصوليا سوداء وأرز أبيض وموز مقلي حلو. أربعة مكونات، كل منها متبل بإتقان. طعم كراكاس.",
  },
  {
    id: "chiles-en-nogada",
    name: "Chiles en Nogada", nameEs: "Chiles en Nogada", nameAr: "تشيليس إن نوغادا",
    category: "comfort-food", regions: ["latin-america"], emoji: "🌶️", calories: "500-650 kcal",
    desc: "Roasted poblano chile stuffed with spiced meat-fruit picadillo, draped in creamy walnut sauce and pomegranate seeds. Red, white, green — the Mexican flag on a plate.",
    descEs: "Chile poblano asado relleno de picadillo de carne y frutas, bañado en salsa de nuez y granada. Rojo, blanco, verde: la bandera mexicana en un plato.",
    descAr: "فلفل بوبلانو محمص محشو بخليط اللحم والفواكه المتبل، مغطى بصلصة الجوز الكريمية وبذور الرمان. أحمر وأبيض وأخضر — العلم المكسيكي في طبق.",
  },
  {
    id: "pastel-de-choclo",
    name: "Pastel de Choclo", nameEs: "Pastel de Choclo", nameAr: "باستيل دي تشوكلو",
    category: "comfort-food", regions: ["latin-america"], emoji: "🌽", calories: "550-680 kcal",
    desc: "Chilean corn pie: seasoned ground beef with olives, chicken, and hard-boiled egg under a sweet corn crust, baked until golden. Chilean comfort baking at its peak.",
    descEs: "Pastel de choclo chileno: carne molida sazonada con aceitunas, pollo y huevo duro bajo una costra de maíz dulce. La mejor repostería reconfortante chilena.",
    descAr: "فطيرة ذرة تشيلية: لحم بقري مفروم متبل مع زيتون ودجاج وبيض مسلوق تحت قشرة ذرة حلوة، مخبوزة حتى تصبح ذهبية. خبز الراحة التشيلي في أبهى صورة.",
  },
];
